// =====================================================================
//  MYTHIC SPELLBOOK — BESTIARY DATA
// =====================================================================

window.MS = window.MS || {};

// ---------- ELEMENTS ----------
MS.ELEMENTS = [
  { id: "fire",       label: "Fire",       hue: 14,  glyph: "✦" },
  { id: "water",      label: "Water",      hue: 220, glyph: "≈" },
  { id: "earth",      label: "Earth",      hue: 35,  glyph: "▲" },
  { id: "wind",       label: "Wind",       hue: 165, glyph: "⌇" },
  { id: "light",      label: "Light",      hue: 50,  glyph: "☀" },
  { id: "shadow",     label: "Shadow",     hue: 280, glyph: "☾" },
  { id: "nature",     label: "Nature",     hue: 120, glyph: "❦" },
  { id: "storm",      label: "Storm",      hue: 250, glyph: "⚡" },
  { id: "ice",        label: "Ice",        hue: 195, glyph: "❄" },
  { id: "metal",      label: "Metal",      hue: 20,  glyph: "⚒" },
  { id: "poison",     label: "Poison",     hue: 95,  glyph: "☠" },
  { id: "psychic",    label: "Psychic",    hue: 305, glyph: "✺" },
  { id: "arcane",     label: "Arcane",     hue: 270, glyph: "✶" },
  { id: "void",       label: "Void",       hue: 290, glyph: "◉" },
  { id: "blood",      label: "Blood",      hue: 0,   glyph: "⚕" },
  { id: "crystal",    label: "Crystal",    hue: 185, glyph: "◈" },
  { id: "corruption", label: "Corruption", hue: 320, glyph: "҂" },
  { id: "spirit",     label: "Spirit",     hue: 175, glyph: "༜" },
  { id: "lava",       label: "Lava",       hue: 8,   glyph: "♨" },
  { id: "sound",      label: "Sound",      hue: 45,  glyph: "♪" },
  { id: "gravity",    label: "Gravity",    hue: 260, glyph: "⊙" },
];
MS.ELEMENT_MAP = Object.fromEntries(MS.ELEMENTS.map(e => [e.id, e]));

// ---------- FACTIONS ----------
MS.FACTIONS = [
  "Warrior","Mage","Rogue","Beast","Bird","Bug","Goblinoid","Demon","Undead",
  "Elemental","Fairy","Dragonkin","Construct","Celestial","Plant","Reptile",
  "Vampire","Slime","Aquatic","Giant","Shapeshifter","Eldritch","Artificer",
  "Necromancer","Samurai","Pirate","Merchant","Scholar","Soldier","Corrupted",
  "Spirit","Berserker","Monk","Divine","Cultist","Tribal","Champion","Swarm","Alien"
].map(name => ({ id: name.toLowerCase(), label: name }));
MS.FACTION_MAP = Object.fromEntries(MS.FACTIONS.map(f => [f.id, f]));

// ---------- THREAT TIERS ----------
MS.TIERS = [
  { id: "common",    label: "Common",    rank: 1, ink: "#5b4a2a" },
  { id: "uncommon",  label: "Uncommon",  rank: 2, ink: "#3e5a2a" },
  { id: "rare",      label: "Rare",      rank: 3, ink: "#2a4a6a" },
  { id: "elite",     label: "Elite",     rank: 4, ink: "#5e2a6a" },
  { id: "legendary", label: "Legendary", rank: 5, ink: "#8a5a14" },
  { id: "mythic",    label: "Mythic",    rank: 6, ink: "#6b1818" },
];
MS.TIER_MAP = Object.fromEntries(MS.TIERS.map(t => [t.id, t]));

// ---------- PASSIVE REGISTRY ----------
MS.PASSIVES = [
  // Core / Stat Buffs
  { id:"regeneration",  group:"Core",       name:"Regeneration",     effect:"Heal 2 HP at start of your turn." },
  { id:"swift",         group:"Core",       name:"Swift",            effect:"+1 movement range." },
  { id:"tough",         group:"Core",       name:"Tough",            effect:"+3 Defense." },
  { id:"magicWard",     group:"Core",       name:"Magic Ward",       effect:"+3 Magic Resist." },
  { id:"warlord",       group:"Core",       name:"Warlord",          effect:"Your units gain +2 Attack." },
  { id:"archmage",      group:"Core",       name:"Archmage",         effect:"Spells cost 1 less energy." },
  { id:"guardian",      group:"Core",       name:"Guardian",         effect:"Adjacent allies take 25% less damage." },
  { id:"inspire",       group:"Core",       name:"Inspire",          effect:"Draw an extra card every 3 turns." },
  { id:"taunt",         group:"Core",       name:"Taunt",            effect:"Enemies in range must attack this unit first." },
  { id:"energySpring",  group:"Core",       name:"Energy Spring",    effect:"+1 energy at start of turn while on field." },
  // Combat triggers
  { id:"thorns",        group:"Combat",     name:"Thorns",           effect:"Reflect 25% damage taken." },
  { id:"lifesteal",     group:"Combat",     name:"Lifesteal",        effect:"Heal 30% of damage dealt." },
  { id:"venomous",      group:"Combat",     name:"Venomous",         effect:"Attacks have 30% chance to poison." },
  { id:"bloodthirst",   group:"Combat",     name:"Bloodthirst",      effect:"Heal 5 HP after killing a unit." },
  { id:"kalonChannel",  group:"Combat",     name:"Kalon Channel",    effect:"On KO: refund 1 Kalon use (cap 3)." },
  // Competitive
  { id:"sturdy",        group:"Competitive",name:"Bedrock",          effect:"At full HP, an attack that would KO leaves 1 HP instead. Once / battle." },
  { id:"moxie",         group:"Competitive",name:"Killer Instinct",  effect:"Each KO grants +2 ATK permanently (max +10)." },
  { id:"divineSmite",   group:"Competitive",name:"Daybreaker",       effect:"First attack each turn deals +25% damage." },
  { id:"adaptability",  group:"Competitive",name:"Elemental Affinity",effect:"STAB hits deal +75% instead of +50%." },
  { id:"sneakAttack",   group:"Competitive",name:"Flanker",          effect:"+30% dmg when an ally is adjacent to target." },
  // Death / Revival
  { id:"raiseFromDead", group:"Death",      name:"Raise From Dead",  effect:"On death: leaves a tombstone; rises at 60% HP if tile stays clear." },
  { id:"rebirthShift",  group:"Death",      name:"Rebirth Shift",    effect:"On death: returns next turn as a unit from the Rebirth Pool." },
  { id:"phoenixRebirth",group:"Death",      name:"Phoenix Rebirth Aura",effect:"Allies dying in aura may revive in flame." },
  { id:"stabilize",     group:"Death",      name:"Stabilize",        effect:"Non-hero units bleed for 3 turns instead of dying; rescuable." },
  // Immortal / Retribution
  { id:"physicalImmortal",group:"Immortal", name:"Unbreakable Body", effect:"Cannot die from PHYSICAL damage — drops to 1 HP instead." },
  { id:"magicalImmortal", group:"Immortal", name:"Soul Shield",      effect:"Cannot die from MAGICAL damage — drops to 1 HP instead." },
  { id:"physicalRetribution",group:"Immortal",name:"Spiked Carapace",effect:"PHYSICAL attackers are instantly slain (heroes immune)." },
  { id:"magicalRetribution", group:"Immortal",name:"Mana Feedback",  effect:"MAGICAL attackers are instantly slain (heroes immune)." },
  // Ascension
  { id:"forcedAscension",group:"Ascension", name:"Forced Ascension", effect:"Auto Kalon-transforms at the configured timing (no charge)." },
  // XCOM
  { id:"predatorsEye",  group:"Reaction",   name:"Predator's Eye",   effect:"Reaction: enemy moves within 2 tiles → free strike (1×/enemy turn)." },
  { id:"hairTrigger",   group:"Reaction",   name:"Hair Trigger",     effect:"Overwatch + Ambush reactions can crit." },
  { id:"coolUnderPressure",group:"Reaction",name:"Cool Under Pressure",effect:"Reactions ignore the 25% damage penalty." },
  { id:"squadSight",    group:"Reaction",   name:"Squad Sight",      effect:"Attack range extends through teammate vision (3 tiles)." },
  { id:"ironWill",      group:"Reaction",   name:"Iron Will",        effect:"Immune to Panic." },
  // Comeback
  { id:"outnumbered",   group:"Comeback",   name:"Underdog",         effect:"While outnumbered, this card costs 0 to play." },
  { id:"weatherborn",   group:"Comeback",   name:"Weatherborn",      effect:"Card costs 0 while ANY weather is active." },
  // Weather-triggered
  { id:"sunbather",     group:"Weather",    name:"Sunbather",        effect:"☀ Sun: heal 4 HP at start of turn." },
  { id:"rainmaker",     group:"Weather",    name:"Rainmaker",        effect:"🌧 Rain: +5 Magic." },
  { id:"dustcloak",     group:"Weather",    name:"Dustcloak",        effect:"🏜 Sandstorm: immune; +1 SPD." },
  { id:"stormborn",     group:"Weather",    name:"Stormborn",        effect:"Any weather: damage +25%." },
  { id:"weatherweaver", group:"Weather",    name:"Weatherweaver",    effect:"Your weather cards last 2 extra turns." },
  { id:"weatherSummoner",group:"Weather",   name:"Weather Summoner", effect:"On summon: calls weather of primary element (4 turns)." },
  { id:"solarFlare",    group:"Weather",    name:"Solar Flare",      effect:"☀ Sun: may attack twice / turn." },
  { id:"radiantAegis",  group:"Weather",    name:"Radiant Aegis",    effect:"☀ Sun: adjacent allies take 25% less damage." },
  { id:"sunforged",     group:"Weather",    name:"Sunforged",        effect:"☀ Sun: super-effective hits capped at 1×." },
  { id:"monsoonMight",  group:"Weather",    name:"Monsoon Might",    effect:"🌧 Rain: +3 ATK and +3 MAG." },
  { id:"tideHealer",    group:"Weather",    name:"Tide Healer",      effect:"🌧 Rain: heal all allies 2 HP at start of turn." },
  { id:"stormChannel",  group:"Weather",    name:"Storm Channel",    effect:"🌧 Rain: +1 energy at start of turn." },
  { id:"sandShroud",    group:"Weather",    name:"Sand Shroud",      effect:"🏜 Sandstorm: enemies +30% miss vs this unit." },
  { id:"dustForged",    group:"Weather",    name:"Dust Forged",      effect:"🏜 Sandstorm: +4 DEF and +4 RES." },
  { id:"mistDancer",    group:"Weather",    name:"Mist Dancer",      effect:"🌫 Mist: attacks cannot miss; +20% crit." },
  { id:"ambushSoul",    group:"Weather",    name:"Ambush Soul",      effect:"🌫 Mist: first attack each turn +50% dmg." },
  { id:"eclipseLord",   group:"Weather",    name:"Eclipse Lord",     effect:"🌑 Eclipse: +30% dmg; ignores 50% DEF/RES." },
  { id:"shadowMeld",    group:"Weather",    name:"Shadow Meld",      effect:"🌑 Eclipse: ranged attacks auto-miss." },
  { id:"bloodLord",     group:"Weather",    name:"Blood Lord",       effect:"🩸 Bloodmoon: lifesteal 50%." },
  { id:"crimsonCovenant",group:"Weather",   name:"Crimson Covenant", effect:"🩸 Bloodmoon: aura +2 ATK / +2 MAG to allies." },
  { id:"lucidThinker",  group:"Weather",    name:"Lucid Thinker",    effect:"🧠 Mind Realm: moves cost 1 less energy." },
  { id:"paradoxGuard",  group:"Weather",    name:"Paradox Guard",    effect:"🌍 Parallel World: SPD inversion cancelled." },
  { id:"tempestSoul",   group:"Weather",    name:"Tempest Soul",     effect:"Any weather: +2 SPD, +1 to all combat stats." },
  { id:"weatherWalker", group:"Weather",    name:"Weather Walker",   effect:"Any weather: +1 movement; immune to sandstorm." },
  // Counter-play
  { id:"trapHunter",    group:"Counter",    name:"Trap Hunter",      effect:"+2 ATK and +1 SPD while any trap is on field." },
  { id:"trapDog",       group:"Counter",    name:"Trap Dog",         effect:"On entering play: reveals every enemy trap." },
  { id:"trapBreaker",   group:"Counter",    name:"Trap Breaker",     effect:"Turn start: disarms one adjacent enemy trap." },
  { id:"wallBreaker",   group:"Counter",    name:"Wall Breaker",     effect:"+50% damage to walls / structures." },
  { id:"surfaceWalker", group:"Counter",    name:"Surface Walker",   effect:"Immune to surface hazards; clears tiles stepped on." },
  { id:"weatherWarden", group:"Counter",    name:"Weather Warden",   effect:"Active weather ends 1 turn sooner each round alive." },
  { id:"geomancer",     group:"Counter",    name:"Geomancer",        effect:"20% / turn to destroy opponent's active Location." },
  { id:"xrayVision",    group:"Counter",    name:"X-Ray Vision",     effect:"Auto-scans all enemy units and heroes." },
  // Tribal / Faction
  { id:"warriorOath",   group:"Tribal",     name:"Warrior's Oath",   effect:"+1 ATK per other ally Warrior (max +5)." },
  { id:"arcaneBond",    group:"Tribal",     name:"Arcane Bond",      effect:"+1 MAG per other ally Mage (max +5)." },
  { id:"packTactics",   group:"Tribal",     name:"Pack Tactics",     effect:"+5% crit per other ally Rogue (max +20%)." },
  { id:"packLeader",    group:"Tribal",     name:"Pack Leader",      effect:"+1 SPD if any other ally Beast on field." },
  { id:"flockFlight",   group:"Tribal",     name:"Flock Flight",     effect:"Becomes Flying while another ally Bird is alive." },
  { id:"swarmInstinct", group:"Tribal",     name:"Swarm Instinct",   effect:"+10% poison-on-hit per other ally Bug (max +30%)." },
  { id:"mobTactics",    group:"Tribal",     name:"Mob Tactics",      effect:"+1 ATK per other ally Goblinoid (max +5)." },
  { id:"hellbound",     group:"Tribal",     name:"Hellbound",        effect:"+1 ATK / +1 MAG per other ally Demon (max +4 each)." },
  { id:"deathlyVigil",  group:"Tribal",     name:"Deathly Vigil",    effect:"Heal 2 HP/turn per other ally Undead (max 6)." },
  { id:"elementBond",   group:"Tribal",     name:"Element Bond",     effect:"+1 MAG per other ally Elemental (max +4)." },
  { id:"faewish",       group:"Tribal",     name:"Faewish",          effect:"10% dodge per other ally Fairy (max 30%)." },
  { id:"dragonsBoon",   group:"Tribal",     name:"Dragon's Boon",    effect:"+2 ATK / +2 MAG per other ally Dragonkin (max +6 each)." },
  { id:"constructed",   group:"Tribal",     name:"Constructed",      effect:"Immune to poison, burn, bleed, infected." },
  { id:"holyAura",      group:"Tribal",     name:"Holy Aura",        effect:"Heal 1 HP/turn per other ally Celestial (max 4)." },
  { id:"rootsOfLife",   group:"Tribal",     name:"Roots of Life",    effect:"Heal 3 HP at start of every turn." },
  { id:"coldScales",    group:"Tribal",     name:"Cold Scales",      effect:"+2 DEF / +2 RES per other Reptile (max +6); immune slow/freeze." },
  { id:"xenoBond",      group:"Tribal",     name:"Xeno Bond",        effect:"Immune to Infected; 25% to Infect on hit." },
  // Element Wards
  { id:"fireWard",      group:"Ward",       name:"Fire Ward",        effect:"Immune to FIRE damage." },
  { id:"waterWard",     group:"Ward",       name:"Water Ward",       effect:"Immune to WATER damage." },
  { id:"earthWard",     group:"Ward",       name:"Earth Ward",       effect:"Immune to EARTH damage." },
  { id:"windWard",      group:"Ward",       name:"Wind Ward",        effect:"Immune to WIND damage." },
  { id:"lightWard",     group:"Ward",       name:"Light Ward",       effect:"Immune to LIGHT damage." },
  { id:"shadowWard",    group:"Ward",       name:"Shadow Ward",      effect:"Immune to SHADOW damage." },
  { id:"natureWard",    group:"Ward",       name:"Nature Ward",      effect:"Immune to NATURE damage." },
  { id:"stormWard",     group:"Ward",       name:"Storm Ward",       effect:"Immune to STORM damage." },
  { id:"iceWard",       group:"Ward",       name:"Ice Ward",         effect:"Immune to ICE damage." },
  { id:"arcaneWard",    group:"Ward",       name:"Arcane Ward",      effect:"Immune to ARCANE damage." },
  { id:"voidWard",      group:"Ward",       name:"Void Ward",        effect:"Immune to VOID damage." },
  { id:"bloodWard",     group:"Ward",       name:"Blood Ward",       effect:"Immune to BLOOD damage." },
  // Faction Wards
  { id:"wardVsWarrior",   group:"Bane",     name:"Champion's Bane",  effect:"Immune to damage from Warriors." },
  { id:"wardVsMage",      group:"Bane",     name:"Spellbreaker",     effect:"Immune to damage from Mages." },
  { id:"wardVsRogue",     group:"Bane",     name:"Eagle Eye",        effect:"Immune to damage from Rogues." },
  { id:"wardVsBeast",     group:"Bane",     name:"Hunter's Mark",    effect:"Immune to damage from Beasts." },
  { id:"wardVsBird",      group:"Bane",     name:"Falconer's Net",   effect:"Immune to damage from Birds." },
  { id:"wardVsBug",       group:"Bane",     name:"Exterminator",     effect:"Immune to damage from Bugs." },
  { id:"wardVsDemon",     group:"Bane",     name:"Sanctified",       effect:"Immune to damage from Demons." },
  { id:"wardVsUndead",    group:"Bane",     name:"Hallowed Flesh",   effect:"Immune to damage from Undead." },
  { id:"wardVsDragon",    group:"Bane",     name:"Dragon Slayer",    effect:"Immune to damage from Dragonkin." },
  { id:"wardVsConstruct", group:"Bane",     name:"Rust Touch",       effect:"Immune to damage from Constructs." },
  { id:"wardVsCelestial", group:"Bane",     name:"Heretic's Armor",  effect:"Immune to damage from Celestials." },
  { id:"wardVsGoblinoid", group:"Bane",     name:"Tribal Defense",   effect:"Immune to damage from Goblinoids." },
];
MS.PASSIVE_MAP = Object.fromEntries(MS.PASSIVES.map(p => [p.id, p]));
MS.PASSIVE_GROUPS = [...new Set(MS.PASSIVES.map(p => p.group))];

// ---------- HELPER ----------
const m = (id, data) => ({ id, ...data });
const blank = () => ({ hp:5, atk:5, def:5, mag:5, res:5, spd:5 });

// ---------- MONSTERS (seed) ----------
// Each monster: id, name, art, factions[], elements[], tier,
//   stats {hp,atk,def,mag,res,spd}, passives[], traits[], lore, habitat, tactics, weaknesses, resistances
//   layout: "boss" | "card"
//   kalon: { name, art, stats, passives, traits, lore } | null
MS.MONSTERS = [
  m("abraxas", {
    name: "Abraxas",
    art: "uploads/Abraxas.png",
    factions: ["divine","eldritch","cultist"],
    elements: ["arcane","void","light","shadow"],
    tier: "mythic", layout: "boss",
    stats: { hp:28, atk:14, def:16, mag:30, res:26, spd:12 },
    passives: ["archmage","weatherweaver","forcedAscension","arcaneWard"],
    traits: ["Four-Orb Sigil","Sourceless Sight","Robe of Tatters"],
    lore: "Before the Spellbook bound the world's letters, Abraxas spoke. Wherever he turns his hooded gaze the elements forget their names and remember only obedience. Cults whisper that the rags he wears are the unwritten chapters of the world — torn loose when he abandoned creation to wander among its ruins.",
    habitat: "Forgotten basilicas at the edges of named maps; threshold storms; the last page of any abandoned tome.",
    tactics: "Opens battles by reordering the weather to match its mood. Channels the four orbs in turn — fire to break formations, water to drown them, earth to bury survivors, arcane to forget they ever lived.",
    weaknesses: ["light","sound"], resistances: ["arcane","void","shadow"],
    kalon: {
      name: "Abraxas — Creator of Source",
      art: "uploads/Abraxas Creator of Source Kalon Mode.png",
      stats: { hp:30, atk:18, def:22, mag:30, res:30, spd:18 },
      passives: ["archmage","forcedAscension","arcaneWard","voidWard","magicalRetribution"],
      traits: ["The Source Restored","Crown of First Words","Genesis Halo"],
      lore: "When the four orbs return to their original arrangement, Abraxas remembers what he was — and the world begins to write itself in his hand. Reality flinches.",
    },
  }),

  m("azathoth", {
    name: "Azathoth",
    art: "uploads/azathoth.png",
    factions: ["eldritch","divine","cultist"],
    elements: ["void","corruption","psychic"],
    tier: "mythic", layout: "boss",
    stats: { hp:30, atk:18, def:14, mag:28, res:22, spd:6 },
    passives: ["weatherSummoner","forcedAscension","voidWard","magicalImmortal","ironWill"],
    traits: ["Idiot Sultan","Pipes of the Outer Court","Dream-Sleeper"],
    lore: "He sleeps and the cosmos exhales his nightmare. Pipers blind to their own song keep him drowsy; awaken him and the chapters that contain you simply stop being written. Scholars who studied him do not exist now, and never did.",
    habitat: "The slumbering throne at the center of nowhere; the unwritten margins of dreamt maps.",
    tactics: "Does not 'fight.' Its presence is the battle. Allied pipers and cultists must be slain first or the field itself begins to unmake heroes one limb at a time.",
    weaknesses: ["sound","light"], resistances: ["void","corruption","psychic","shadow"],
  }),

  m("cenregon", {
    name: "Cenregon",
    art: "uploads/Cenregon.png",
    factions: ["celestial","champion","divine"],
    elements: ["light","spirit","arcane"],
    tier: "legendary", layout: "boss",
    stats: { hp:24, atk:18, def:18, mag:22, res:20, spd:14 },
    passives: ["holyAura","divineSmite","guardian","wardVsDemon"],
    traits: ["Hopebearer","Last Lantern","Oathbound"],
    lore: "Called when no other answer remains. Cenregon arrives by the road that only the desperate can pave — a path made of the names of the dead spoken aloud, in order, without weeping.",
    habitat: "Final stands; reliquaries; any battlefield where surrender has already happened in someone's heart.",
    tactics: "Holds the line. Refuses to fall. Each ally that drops within his aegis steels him further until the field cannot bear him.",
    weaknesses: ["shadow","corruption"], resistances: ["light","arcane"],
    kalon: {
      name: "Cenregon — The Final Hope",
      art: "uploads/Cenregon The Final Hope Kalon Mode.png",
      stats: { hp:30, atk:24, def:22, mag:26, res:26, spd:20 },
      passives: ["divineSmite","guardian","phoenixRebirth","holyAura","wardVsDemon"],
      traits: ["Lantern Unsheathed","Oath of the Dying","Light Without Source"],
      lore: "When the last ally falls, Cenregon stops being a knight and becomes the answer. The lantern opens. The room remembers what it was before the dark.",
    },
  }),

  m("efreet", {
    name: "Efreet",
    art: "uploads/Efreet.png",
    factions: ["demon","elemental","berserker"],
    elements: ["fire","lava","shadow"],
    tier: "legendary", layout: "boss",
    stats: { hp:26, atk:24, def:20, mag:20, res:14, spd:14 },
    passives: ["solarFlare","monsoonMight","fireWard","bloodthirst"],
    traits: ["Hellbinder","Smoldering Oath","Burning Armaments"],
    lore: "Bound jinn of the inner furnaces. Where it walks the air refuses to be air; where it stops the ground refuses to be ground. Pacts struck with Efreet always end the way kindling ends.",
    habitat: "Black-glass deserts above subducted magma; ruined caravanserai; the long shadow of any unfinished altar.",
    tactics: "Charges. Burns the field. Refuses parlay until every banner is ash, then offers terms to the kneeling.",
    weaknesses: ["water","ice"], resistances: ["fire","lava","shadow"],
    kalon: {
      name: "Efreet — Fire Jinn of Hell",
      art: "uploads/Efreet Fire  jinn Of Hell Kalon Mode.png",
      stats: { hp:30, atk:30, def:24, mag:24, res:18, spd:18 },
      passives: ["solarFlare","bloodthirst","physicalRetribution","fireWard","hellbound"],
      traits: ["Crown of Vow-Smoke","Sword Made of Promise","Hell-Tempered"],
      lore: "The bindings burn away. What remains is not a creature, but the heat of a pact remembered too long.",
    },
  }),

  m("zhongkui", {
    name: "Zhong Kui",
    art: "uploads/Zhong Kui.png",
    factions: ["champion","spirit","monk"],
    elements: ["spirit","shadow","arcane"],
    tier: "legendary", layout: "boss",
    stats: { hp:24, atk:22, def:18, mag:22, res:22, spd:18 },
    passives: ["wardVsDemon","wardVsUndead","divineSmite","ironWill"],
    traits: ["Ghost Catcher","Vermilion Brush","Failing Scholar"],
    lore: "Once a scholar wronged at the gates of court, now the doomed's only courteous executioner. He files the dead. He fines the lingering. He drinks alone.",
    habitat: "Lantern-lit threshold shrines; the seventh hour of a ghost month; any corridor where a debt was never paid.",
    tactics: "Catches first, cuts second. Ranged abilities are denied by his calligraphy of binding; melee attackers find the brush has already written their name in the registry of the dead.",
    weaknesses: ["light","sound"], resistances: ["shadow","spirit"],
    kalon: {
      name: "Zhong Kui — Catcher of the Doomed",
      art: "uploads/Zhong Kui Ghost cacther of the doomed Kalon Mode.png",
      stats: { hp:28, atk:28, def:22, mag:26, res:26, spd:24 },
      passives: ["divineSmite","wardVsDemon","wardVsUndead","predatorsEye","ironWill"],
      traits: ["Brush of Final Verdict","Lantern of No Reprieve","Office of the Doomed"],
      lore: "The ink runs black. The case is closed. There is no appeal in this court.",
    },
  }),

  m("zeus", {
    name: "Zeus",
    art: "uploads/Zues.png",
    factions: ["divine","champion","elemental"],
    elements: ["storm","light","sound"],
    tier: "legendary", layout: "boss",
    stats: { hp:26, atk:24, def:18, mag:26, res:20, spd:22 },
    passives: ["stormborn","stormChannel","warlord","wardVsGoblinoid"],
    traits: ["Sky-Father","Bolt-Bearer","Verdict from On High"],
    lore: "Old, vain, still terrifying. The thunder waits on him as on a master. Mortals who claim his patronage rarely live long enough to brag twice.",
    habitat: "Storm-cradle peaks; ruined coliseums; the moment after the lightning before the sound arrives.",
    tactics: "Opens with a single bolt to break formations, then descends. Allies orbit; enemies do not.",
    weaknesses: ["earth","metal"], resistances: ["storm","light"],
    kalon: {
      name: "Zeus — God of Thunder",
      art: "uploads/zues God of Thunder Kalon Mode.png",
      stats: { hp:30, atk:30, def:22, mag:30, res:24, spd:26 },
      passives: ["stormborn","weatherSummoner","stormChannel","stormWard","forcedAscension"],
      traits: ["Throne of Static","Lightning Without Weather","Olympian Roar"],
      lore: "He stops pretending he is one of many. The sky becomes punctuation for his sentences.",
    },
  }),

  m("disguys", {
    name: "Disguys Stone",
    art: "uploads/Disguys Stone.png",
    factions: ["construct","tribal","corrupted"],
    elements: ["earth","crystal","void"],
    tier: "elite", layout: "boss",
    stats: { hp:28, atk:14, def:26, mag:8, res:18, spd:4 },
    passives: ["tough","taunt","earthWard","constructed"],
    traits: ["Misshapen","Mouth-Pits","Old Idol Bones"],
    lore: "Hunters carved it from a god's collapsed altar and the carving did not stop when they did. It moves on its own time and remembers their faces in the slow way mountains remember rain.",
    habitat: "Quarried temple-floors; mounds that local maps refuse to chart twice the same way.",
    tactics: "Roots in. Lets the field come to it. Slow blows; each one rearranges teeth and terrain together.",
    weaknesses: ["arcane","sound"], resistances: ["earth","metal","crystal"],
    kalon: {
      name: "Disguys — The Hunted Stone",
      art: "uploads/Disguys The hunted Stone Kalon Mode.png",
      stats: { hp:30, atk:22, def:30, mag:14, res:24, spd:10 },
      passives: ["tough","physicalRetribution","earthWard","constructed","trapHunter"],
      traits: ["Marked Stone","Vengeance Geometry","Cracked Open"],
      lore: "Once the hunt finds the hunters, the stone stops being a quarry and becomes the question. The answer is short.",
    },
  }),

  m("haunted_house", {
    name: "Haunted House",
    art: "uploads/Haunted house.png",
    factions: ["undead","spirit","construct"],
    elements: ["shadow","spirit","corruption"],
    tier: "elite", layout: "boss",
    stats: { hp:26, atk:12, def:24, mag:20, res:22, spd:6 },
    passives: ["taunt","raiseFromDead","shadowWard","sandShroud"],
    traits: ["Walls That Remember","Doors That Choose","Hungry Threshold"],
    lore: "Not a place that is haunted but a haunting that grew walls. The deeds list it as 'vacant.' The neighbors list it as 'last seen.'",
    habitat: "End-of-cul-de-sac lots; foreclosure listings that come back; any address that arrives by mail without being written.",
    tactics: "Lures. Closes. The fight begins only after the heroes accept its invitation, and by then the floorplan has already eaten the exits.",
    weaknesses: ["fire","light"], resistances: ["shadow","spirit"],
    kalon: {
      name: "Haunted House — Demon's Home",
      art: "uploads/Huanted house Demons home Kalon Mode.png",
      stats: { hp:30, atk:18, def:28, mag:26, res:26, spd:10 },
      passives: ["taunt","raiseFromDead","shadowWard","magicalRetribution","weatherSummoner"],
      traits: ["Hellfloor","Tenant of Last Resort","Door Where No Door Was"],
      lore: "The lease was always in someone else's name. The house signs it now in its own blood and the contract begins.",
    },
  }),

  m("giant_spider", {
    name: "Giant Spider",
    art: "uploads/giant Spider.png",
    factions: ["beast","bug","swarm"],
    elements: ["poison","shadow","nature"],
    tier: "rare", layout: "boss",
    stats: { hp:18, atk:16, def:10, mag:6, res:8, spd:18 },
    passives: ["venomous","swarmInstinct","sneakAttack","trapHunter"],
    traits: ["Eight-Eyed Patience","Silk-Lung","Web-Master"],
    lore: "Older than the cave it ate to make a home. Its silk is patient as winter; what it catches, it keeps named.",
    habitat: "Subterranean galleries; chimney-flues of abandoned mills; the slow corners of any forest where the songbirds stop.",
    tactics: "Spins, then waits. Ambushes the slowest first. Drags survivors into the dark where the math turns.",
    weaknesses: ["fire","light"], resistances: ["poison","shadow"],
    kalon: {
      name: "Giant Spider — Voltage Legs",
      art: "uploads/giant Spider Votage Legs Kalon Mode.png",
      stats: { hp:22, atk:24, def:14, mag:18, res:14, spd:26 },
      passives: ["venomous","stormborn","predatorsEye","sneakAttack","stormWard"],
      traits: ["Static Silk","Eight Cathodes","Hunger Made Faster"],
      lore: "Storm-fed and starvation-thin. The web hums. The mistake is moving.",
    },
  }),

  m("turtle_10k", {
    name: "10,000 Turtle",
    art: "uploads/10000 turtle.png",
    factions: ["beast","aquatic","champion"],
    elements: ["water","earth","spirit"],
    tier: "legendary", layout: "boss",
    stats: { hp:30, atk:10, def:28, mag:16, res:26, spd:4 },
    passives: ["tough","regeneration","waterWard","earthWard"],
    traits: ["Continent-Backed","Ten Thousand Seasons","World-Pace"],
    lore: "Counts time the way mountains count rain. The shell remembers shorelines that the maps have since forgotten. It will outlast this bestiary.",
    habitat: "Inland seas that were once oceans; sacred reed-marshes; the slow center of any tide.",
    tactics: "Withdraws to absorb. Emerges to displace. The field changes shape around it without consent.",
    weaknesses: ["sound","arcane"], resistances: ["water","earth"],
    kalon: {
      name: "10,000 Turtle — Krystal Anomaly",
      art: "uploads/Krystal Anomoly 10000 turtle.png",
      stats: { hp:30, atk:18, def:30, mag:26, res:30, spd:10 },
      passives: ["tough","regeneration","waterWard","earthWard","magicalImmortal"],
      traits: ["Krystallized Shell","Anomalous Age","Geode-Heart"],
      lore: "The shell goes crystalline. Time inside the carapace counts down instead of up. Reality complains.",
    },
  }),

  m("bahamut", {
    name: "Bahamut, King of Good Dragons",
    art: "uploads/Bahamut King Of Good Dragons.png",
    factions: ["dragonkin","divine","celestial"],
    elements: ["light","arcane","storm"],
    tier: "mythic", layout: "boss",
    stats: { hp:30, atk:26, def:22, mag:28, res:24, spd:20 },
    passives: ["dragonsBoon","warlord","holyAura","lightWard","wardVsDemon"],
    traits: ["Silver Crown","Roar of Verdict","Wings of Mercy and Wrath"],
    lore: "The platinum king. Kindness in him is not softness — it is the long memory of a creature that has weighed mercy against extinction and chosen, again, mercy.",
    habitat: "High cloud-cathedrals; the eye of a holy storm; the highest point on any battlefield where a dragon stoops to land.",
    tactics: "Single decisive passes. Refuses small fights. When the field commits, he commits — and ends it.",
    weaknesses: ["shadow","corruption"], resistances: ["light","arcane"],
  }),

  m("vintrius", {
    name: "Vintrius, Creator of Everything",
    art: "uploads/Vintrius Creator of Everything.png",
    factions: ["divine","celestial","eldritch"],
    elements: ["spirit","light","arcane","void"],
    tier: "mythic", layout: "boss",
    stats: { hp:30, atk:18, def:22, mag:30, res:30, spd:18 },
    passives: ["archmage","forcedAscension","arcaneWard","magicalImmortal","holyAura"],
    traits: ["Tree-of-Worlds Bearer","Starfield Skin","Wings of First Hours"],
    lore: "He holds creation as a thing small enough to cup. The cup is not small. He is.",
    habitat: "Before any map; behind any horizon you can name; above any altar that still works.",
    tactics: "Speaks. Rearranges. The battle changes premise mid-turn — heroes that survived the first exchange will find the rules quietly different.",
    weaknesses: ["void"], resistances: ["light","arcane","spirit"],
  }),

  // ---- "card" grunts: stats lighter, lore short ----
  m("zombie", {
    name: "Zombie",
    art: "uploads/Zombie.png",
    factions: ["undead","corrupted","swarm"],
    elements: ["corruption","shadow"],
    tier: "common", layout: "card",
    stats: { hp:10, atk:8, def:4, mag:2, res:4, spd:6 },
    passives: ["raiseFromDead"],
    traits: ["Slow Hunger"],
    lore: "The dead who forgot the punchline of being dead.",
    habitat: "Mass graves; thaw-stricken bog roads.",
    tactics: "Lurch. Bite. Refuse to stop.",
    weaknesses: ["fire","light"], resistances: ["shadow"],
  }),
  m("abomination", {
    name: "Abomination",
    art: "uploads/abomination.png",
    factions: ["undead","corrupted","berserker"],
    elements: ["corruption","blood"],
    tier: "uncommon", layout: "card",
    stats: { hp:16, atk:14, def:8, mag:4, res:6, spd:8 },
    passives: ["bloodthirst","thorns"],
    traits: ["Stitched Wrong"],
    lore: "Several deaths agreed too late to be separate.",
    habitat: "Failed crypts; battlefield pyres half-extinguished.",
    tactics: "Tank a hit, return three.",
    weaknesses: ["light","fire"], resistances: ["shadow","blood"],
  }),
  m("cave_troll", {
    name: "Cave Troll",
    art: "uploads/Cave Troll.png",
    factions: ["giant","tribal","beast"],
    elements: ["earth","shadow"],
    tier: "uncommon", layout: "card",
    stats: { hp:22, atk:18, def:14, mag:2, res:6, spd:8 },
    passives: ["regeneration","tough"],
    traits: ["Cudgel-Arm"],
    lore: "Big. Slow. Heals through it.",
    habitat: "Sunless galleries; ruined mineshafts.",
    tactics: "Walks at you. Keeps walking.",
    weaknesses: ["fire","light"], resistances: ["earth","shadow"],
  }),
  m("ice_troll", {
    name: "Ice Troll",
    art: "uploads/Ice Troll.png",
    factions: ["giant","tribal","beast"],
    elements: ["ice","shadow"],
    tier: "uncommon", layout: "card",
    stats: { hp:22, atk:18, def:14, mag:4, res:10, spd:8 },
    passives: ["regeneration","iceWard"],
    traits: ["Frost-Knit Hide"],
    lore: "Heals where the cold tells it to.",
    habitat: "Glacial cracks; snow-eaten passes.",
    tactics: "Walks at you. Slower. Colder.",
    weaknesses: ["fire"], resistances: ["ice","shadow"],
  }),
  m("dire_wolf", {
    name: "Dire Wolf",
    art: "uploads/Dire Wolf.png",
    factions: ["beast","tribal"],
    elements: ["shadow","wind"],
    tier: "common", layout: "card",
    stats: { hp:14, atk:14, def:8, mag:2, res:6, spd:18 },
    passives: ["packLeader","sneakAttack"],
    traits: ["Pack-Bound"],
    lore: "Never one. Never two. Always enough.",
    habitat: "Pine ridge; the bad side of a moon.",
    tactics: "Flanks. Picks slowest target. Pulls down.",
    weaknesses: ["fire","light"], resistances: ["shadow"],
  }),
  m("giant_snake", {
    name: "Giant Snake",
    art: "uploads/Giant Snake.png",
    factions: ["beast","reptile"],
    elements: ["poison","earth"],
    tier: "uncommon", layout: "card",
    stats: { hp:18, atk:16, def:8, mag:4, res:8, spd:14 },
    passives: ["venomous","coldScales"],
    traits: ["Constrictor"],
    lore: "Older than the path that learned to avoid it.",
    habitat: "River-bend reed beds; ruined irrigation works.",
    tactics: "Strike. Coil. Wait for the breathing to slow.",
    weaknesses: ["ice","fire"], resistances: ["poison","earth"],
  }),
  m("giant_roach", {
    name: "Giant Roach",
    art: "uploads/Giant Roach.png",
    factions: ["bug","swarm","corrupted"],
    elements: ["corruption","poison"],
    tier: "common", layout: "card",
    stats: { hp:10, atk:6, def:8, mag:2, res:10, spd:14 },
    passives: ["swarmInstinct","constructed"],
    traits: ["Survives Everything"],
    lore: "When the chapter closes, this is the species that closes it.",
    habitat: "Sewers; the back of every other bestiary.",
    tactics: "Numbers. Always numbers.",
    weaknesses: ["fire"], resistances: ["corruption","poison"],
  }),
  m("chain_ape", {
    name: "Chain Ape",
    art: "uploads/Chain Ape.png",
    factions: ["beast","berserker","tribal"],
    elements: ["metal","earth"],
    tier: "rare", layout: "card",
    stats: { hp:22, atk:22, def:12, mag:2, res:8, spd:12 },
    passives: ["wallBreaker","warriorOath"],
    traits: ["Chain-Whipped"],
    lore: "The chains were meant to hold it. They held instead onto it.",
    habitat: "Collapsed coliseums; mining camps gone wrong.",
    tactics: "Sweeps a wide arc. Picks targets up.",
    weaknesses: ["arcane","sound"], resistances: ["metal","earth"],
  }),
  m("mutant_dog", {
    name: "Mutant Dog",
    art: "uploads/Mutant dog.png",
    factions: ["beast","corrupted"],
    elements: ["corruption","shadow"],
    tier: "uncommon", layout: "card",
    stats: { hp:14, atk:16, def:6, mag:4, res:6, spd:16 },
    passives: ["packLeader","venomous"],
    traits: ["Three-Jaw"],
    lore: "Loyal still, to something we don't keep records of.",
    habitat: "Field-trial ruins; backwoods kennels.",
    tactics: "Lunge. Tear. Spit. Repeat.",
    weaknesses: ["light","fire"], resistances: ["shadow","corruption"],
  }),
  m("scp_999", {
    name: "Scp-999",
    art: "uploads/Scp-999.png",
    factions: ["slime","spirit","celestial"],
    elements: ["spirit","light"],
    tier: "rare", layout: "card",
    stats: { hp:18, atk:4, def:8, mag:18, res:18, spd:10 },
    passives: ["holyAura","tideHealer","wardVsDemon"],
    traits: ["Joy-Giver"],
    lore: "Soothes the worst of you, then dissolves it.",
    habitat: "Containment vents; broken hearts.",
    tactics: "Heals allies; refuses to harm.",
    weaknesses: ["shadow"], resistances: ["light","spirit"],
  }),
  m("scp_076", {
    name: "Scp-076",
    art: "uploads/Scp-076.png",
    factions: ["champion","corrupted","berserker"],
    elements: ["blood","shadow"],
    tier: "legendary", layout: "card",
    stats: { hp:24, atk:28, def:18, mag:8, res:14, spd:22 },
    passives: ["moxie","raiseFromDead","bloodthirst"],
    traits: ["Re-Sealed Repeatedly"],
    lore: "Comes back angrier each time the box is closed.",
    habitat: "Sealed sarcophagus; the rooms after.",
    tactics: "Closes distance. Does not stop.",
    weaknesses: ["light","arcane"], resistances: ["blood","shadow"],
  }),
  m("typhon", {
    name: "Typhon",
    art: "uploads/Typhon.png",
    factions: ["giant","elemental","eldritch"],
    elements: ["storm","fire","wind"],
    tier: "legendary", layout: "card",
    stats: { hp:28, atk:24, def:20, mag:24, res:18, spd:14 },
    passives: ["stormborn","weatherSummoner","stormWard"],
    traits: ["Hundred-Headed"],
    lore: "Father of monsters in chapters too old to print.",
    habitat: "Volcanic ranges; sky-broken places.",
    tactics: "Calls weather. Means it.",
    weaknesses: ["earth","metal"], resistances: ["storm","fire"],
  }),
  m("scylla", {
    name: "Scylla",
    art: "uploads/scylla.png",
    factions: ["aquatic","beast","eldritch"],
    elements: ["water","shadow"],
    tier: "legendary", layout: "card",
    stats: { hp:26, atk:20, def:16, mag:18, res:16, spd:16 },
    passives: ["tideHealer","monsoonMight","waterWard"],
    traits: ["Six-Necked Hunger"],
    lore: "Once a maiden, then a strait, then a sentence in a sailor's last letter.",
    habitat: "Narrow water; the strait between sense and getting through.",
    tactics: "Picks one head's worth of victim per pass.",
    weaknesses: ["light","sound"], resistances: ["water","shadow"],
  }),
  m("sakla", {
    name: "Sakla",
    art: "uploads/sakla.png",
    factions: ["eldritch","cultist","corrupted"],
    elements: ["void","corruption","blood"],
    tier: "legendary", layout: "card",
    stats: { hp:24, atk:18, def:14, mag:26, res:20, spd:14 },
    passives: ["weatherSummoner","voidWard","magicalRetribution"],
    traits: ["False Demiurge"],
    lore: "Calls itself the maker. The proof is suspiciously absent.",
    habitat: "Heretic temples; warped seminaries.",
    tactics: "Maddens first. Kills second.",
    weaknesses: ["light"], resistances: ["void","corruption"],
  }),
  m("hayyot", {
    name: "Hayyot",
    art: "uploads/Hayyot.png",
    factions: ["celestial","divine","eldritch"],
    elements: ["light","spirit","arcane"],
    tier: "legendary", layout: "card",
    stats: { hp:26, atk:18, def:20, mag:26, res:24, spd:18 },
    passives: ["holyAura","lightWard","wardVsDemon"],
    traits: ["Four-Faced"],
    lore: "Wheels within wheels and judgement within both.",
    habitat: "Cathedrals that hum at the wrong hour.",
    tactics: "Holds station. Decides.",
    weaknesses: ["shadow"], resistances: ["light","arcane"],
  }),
  m("ra", {
    name: "Ra, The Sun God",
    art: "uploads/Ra The Sun God Sprite.png",
    factions: ["divine","celestial","elemental"],
    elements: ["fire","light","sound"],
    tier: "legendary", layout: "card",
    stats: { hp:26, atk:22, def:18, mag:28, res:20, spd:20 },
    passives: ["solarFlare","sunbather","fireWard"],
    traits: ["Sun-Bound"],
    lore: "The day belongs to him; the night merely tolerates the day.",
    habitat: "Pyramidal sanctums; noon, exactly.",
    tactics: "Burns. Heals allies in light. Rules.",
    weaknesses: ["shadow"], resistances: ["fire","light"],
  }),
  m("phoenix", {
    name: "Flaming Phoenix of the Sun",
    art: "uploads/flaming phoenix of the sun.png",
    factions: ["bird","celestial","elemental"],
    elements: ["fire","light"],
    tier: "rare", layout: "card",
    stats: { hp:18, atk:14, def:10, mag:20, res:16, spd:22 },
    passives: ["phoenixRebirth","fireWard","solarFlare"],
    traits: ["Self-Burner"],
    lore: "Falls, burns, returns. The schedule is not your business.",
    habitat: "Solar pyres; high-altitude shrines.",
    tactics: "Dies once on purpose. Costs you.",
    weaknesses: ["water"], resistances: ["fire","light"],
  }),
  m("flytress", {
    name: "Flytress",
    art: "uploads/Flytress.png",
    factions: ["bug","swarm","corrupted"],
    elements: ["poison","corruption"],
    tier: "uncommon", layout: "card",
    stats: { hp:14, atk:10, def:6, mag:8, res:8, spd:16 },
    passives: ["swarmInstinct","venomous"],
    traits: ["Hum-Cloud"],
    lore: "What a thousand flies become when they choose a leader.",
    habitat: "Carrion fields; ill-shut crypts.",
    tactics: "Blinds. Bleeds. Numbers.",
    weaknesses: ["fire","wind"], resistances: ["poison","corruption"],
  }),
  m("brainjelly", {
    name: "Brainjelly",
    art: "uploads/Brainjelly.png",
    factions: ["aquatic","eldritch","slime"],
    elements: ["psychic","water"],
    tier: "rare", layout: "card",
    stats: { hp:14, atk:6, def:6, mag:22, res:20, spd:8 },
    passives: ["lucidThinker","magicWard","ironWill"],
    traits: ["Wet Thought"],
    lore: "Thinks at you until you remember it.",
    habitat: "Deep tide; cathedral aquaria.",
    tactics: "Mind-stun. Drift. Compel.",
    weaknesses: ["sound","metal"], resistances: ["psychic","water"],
  }),
  m("scp_046", {
    name: "Scp-046",
    art: "uploads/SCP-046.png",
    factions: ["construct","corrupted","plant"],
    elements: ["nature","corruption"],
    tier: "rare", layout: "card",
    stats: { hp:22, atk:12, def:18, mag:10, res:14, spd:4 },
    passives: ["taunt","trapDog","rootsOfLife"],
    traits: ["Predatory Holly"],
    lore: "Decorates with what wandered in.",
    habitat: "Overgrown courtyards; off-trail clearings.",
    tactics: "Lures. Holds. Digests slowly.",
    weaknesses: ["fire"], resistances: ["nature","corruption"],
  }),
  m("xenotail", {
    name: "Xenotail",
    art: "uploads/Xenotail.png",
    factions: ["alien","beast","corrupted"],
    elements: ["void","corruption"],
    tier: "rare", layout: "card",
    stats: { hp:18, atk:18, def:10, mag:10, res:10, spd:18 },
    passives: ["xenoBond","sneakAttack","venomous"],
    traits: ["Tail-First"],
    lore: "Wherever it ends, it's already been.",
    habitat: "Wrecked transports; quarantine zones.",
    tactics: "Strike from above. Always above.",
    weaknesses: ["fire","sound"], resistances: ["void","corruption"],
  }),
  m("mothership", {
    name: "Mothership",
    art: "uploads/Mothership.png",
    factions: ["alien","construct","artificer"],
    elements: ["metal","arcane","void"],
    tier: "legendary", layout: "card",
    stats: { hp:30, atk:18, def:26, mag:22, res:24, spd:8 },
    passives: ["constructed","weatherSummoner","arcaneWard"],
    traits: ["Hull of Cold Stars"],
    lore: "It does not land. The land comes to it.",
    habitat: "Upper atmosphere; the hour before a sky goes wrong.",
    tactics: "Hovers. Deploys. Decides.",
    weaknesses: ["storm","blood"], resistances: ["metal","void"],
  }),
  m("scp_5000", {
    name: "Scp-5000",
    art: "uploads/SCP-5000.png",
    factions: ["construct","artificer","corrupted"],
    elements: ["metal","void"],
    tier: "elite", layout: "card",
    stats: { hp:24, atk:22, def:18, mag:18, res:18, spd:14 },
    passives: ["constructed","wallBreaker","magicalImmortal"],
    traits: ["Why?-Suit"],
    lore: "The reason for it is more dangerous than it.",
    habitat: "Shelved storerooms; the basement under the basement.",
    tactics: "Walks through walls. Asks no questions.",
    weaknesses: ["arcane"], resistances: ["metal","void"],
  }),
  m("scp_001_crimson", {
    name: "SCP-001 Crimson King",
    art: "uploads/SCP-001 Crimson King.png",
    factions: ["divine","eldritch","cultist"],
    elements: ["blood","shadow","corruption"],
    tier: "mythic", layout: "card",
    stats: { hp:30, atk:24, def:22, mag:28, res:24, spd:14 },
    passives: ["bloodLord","crimsonCovenant","bloodWard","wardVsCelestial"],
    traits: ["Throne of Cinders"],
    lore: "Crowned in a chapter that the editors quietly removed.",
    habitat: "Last sanctum; ash-floored court.",
    tactics: "Rules. Lets you bleed for the privilege.",
    weaknesses: ["light"], resistances: ["blood","shadow"],
  }),
  m("scp_001_gate", {
    name: "SCP-001 Gate Guardian",
    art: "uploads/SCP-001 Gate Guardian.png",
    factions: ["celestial","divine","champion"],
    elements: ["light","fire","spirit"],
    tier: "mythic", layout: "card",
    stats: { hp:30, atk:26, def:24, mag:26, res:24, spd:16 },
    passives: ["guardian","holyAura","lightWard","divineSmite"],
    traits: ["Flaming Sword","Garden-Keeper"],
    lore: "Stands where you are not invited.",
    habitat: "Threshold of the first garden.",
    tactics: "Refuses entry. Means it.",
    weaknesses: ["shadow"], resistances: ["light","fire"],
  }),
  m("scp_049_kalon", {
    name: "SCP-049 Divine Kalon",
    art: "uploads/SCP-049 Divine Kalon Mode.png",
    factions: ["necromancer","champion","corrupted"],
    elements: ["spirit","corruption","blood"],
    tier: "legendary", layout: "card",
    stats: { hp:26, atk:22, def:20, mag:24, res:22, spd:18 },
    passives: ["forcedAscension","raiseFromDead","bloodLord","wardVsUndead"],
    traits: ["Plague-Bright Mask"],
    lore: "Cures by replacing.",
    habitat: "Hospitals after dark; archives that hum.",
    tactics: "Touches. Re-purposes.",
    weaknesses: ["light"], resistances: ["corruption","spirit"],
  }),
  // ---- smaller card grunts you can fill in stats for ----
  m("batcoon",          { name:"Batcoon",            art:"uploads/Batcoon.png",            factions:["beast","shapeshifter"], elements:["shadow","wind"],   tier:"common",   layout:"card", stats:{hp:8,atk:8,def:4,mag:4,res:4,spd:14}, passives:["sneakAttack"], traits:["Trash-Wing"], lore:"Bandit-mask, bat-wings, no manners.", habitat:"Refuse heaps; old barns.", tactics:"Snatch and run.", weaknesses:["light"], resistances:["shadow"]}),
  m("abra_fairies",     { name:"Abra Fairies",       art:"uploads/Abra Fairies.png",       factions:["fairy","mage","swarm"], elements:["arcane","light"], tier:"common",   layout:"card", stats:{hp:6,atk:4,def:4,mag:12,res:10,spd:14}, passives:["faewish","arcaneBond"], traits:["Wing-Flicker"], lore:"Tiny. Pluralized. Annoying.", habitat:"Moonlit groves.", tactics:"Bind, distract.", weaknesses:["metal"], resistances:["arcane"]}),
  m("angel_mistakes",   { name:"Angel Mistakes",     art:"uploads/Angel Mistakes.png",     factions:["celestial","corrupted","spirit"], elements:["light","corruption"], tier:"rare", layout:"card", stats:{hp:18,atk:14,def:12,mag:18,res:16,spd:14}, passives:["holyAura","thorns"], traits:["Wing Wrong"], lore:"The first try. They left it.", habitat:"Forgotten reliquaries.", tactics:"Mourns at you.", weaknesses:["arcane"], resistances:["light","corruption"]}),
  m("aqua_pup",         { name:"Aqua Pup",           art:"uploads/Auqa Pup.png",           factions:["beast","aquatic"],     elements:["water"],          tier:"common", layout:"card", stats:{hp:10,atk:6,def:6,mag:8,res:10,spd:12}, passives:["tideHealer"], traits:["Wet Friend"], lore:"Yips in tide-pools.", habitat:"Estuaries.", tactics:"Splashes. Bites.", weaknesses:["storm"], resistances:["water"]}),
  m("baby_geomax",      { name:"Baby GeoMax",        art:"uploads/Baby GeoMax.png",        factions:["construct","elemental"], elements:["earth","crystal"], tier:"common", layout:"card", stats:{hp:12,atk:6,def:14,mag:8,res:12,spd:6}, passives:["earthWard","tough"], traits:["Pebble-Hearted"], lore:"Will be enormous one day.", habitat:"Geode caves.", tactics:"Hides. Grows.", weaknesses:["sound"], resistances:["earth","crystal"]}),
  m("geomax_final",     { name:"GeoMax, Final One of the Beginning", art:"uploads/Geomax The Final One Of The Beginning.png", factions:["construct","elemental","champion"], elements:["earth","crystal","arcane"], tier:"mythic", layout:"boss", stats:{hp:30,atk:24,def:30,mag:24,res:28,spd:14}, passives:["earthWard","tough","constructed","physicalRetribution","forcedAscension"], traits:["First-Stone Crown","Continent-Memory"], lore:"It remembers being the first piece set. It remembers being set down.", habitat:"Bedrock altars; the floor under the floor.", tactics:"Steps once. The field reorganizes.", weaknesses:["sound","arcane"], resistances:["earth","crystal","metal"]}),
  m("blazing_tigershark",{name:"Blazing Tigershark", art:"uploads/Blazing Tigershark.png", factions:["beast","aquatic"],    elements:["fire","water"],  tier:"rare",   layout:"card", stats:{hp:18,atk:18,def:10,mag:12,res:10,spd:18}, passives:["bloodthirst","fireWard"], traits:["Boiling Wake"], lore:"Steams as it strikes.", habitat:"Black coasts.", tactics:"Charges. Bites.", weaknesses:["earth"], resistances:["fire","water"]}),
  m("blaznet_rex",      { name:"Blaznet Rex",        art:"uploads/Blaznet Rex.png",        factions:["beast","reptile","berserker"], elements:["fire","metal"], tier:"elite", layout:"card", stats:{hp:24,atk:24,def:18,mag:8,res:12,spd:16}, passives:["wallBreaker","fireWard"], traits:["Iron-Toothed"], lore:"King of a small extinction.", habitat:"Volcanic plains.", tactics:"Rampage.", weaknesses:["water"], resistances:["fire","metal"]}),
  m("bogar",            { name:"Bogar the Golden Dire Wolf", art:"uploads/Bogar the golden dire Wolf.png", factions:["beast","champion","tribal"], elements:["light","wind"], tier:"rare", layout:"card", stats:{hp:20,atk:18,def:14,mag:6,res:10,spd:20}, passives:["packLeader","divineSmite"], traits:["Sun-Furred"], lore:"Alpha to a vanished pack.", habitat:"Sun-bleached ridges.", tactics:"Picks. Strikes. Howls.", weaknesses:["shadow"], resistances:["light"]}),
  m("camp_knight",      { name:"Camp Knight",        art:"uploads/Camp Knight.png",        factions:["warrior","soldier","champion"], elements:["metal","fire"], tier:"uncommon", layout:"card", stats:{hp:18,atk:16,def:16,mag:4,res:10,spd:10}, passives:["warriorOath","guardian"], traits:["Plate-Fed"], lore:"Sleeps in mail.", habitat:"Garrisoned passes.", tactics:"Shield. Strike.", weaknesses:["arcane"], resistances:["metal"]}),
  m("camp_mage",        { name:"Camp Mage",          art:"uploads/Camp mage.png",          factions:["mage","scholar"],      elements:["arcane","light"], tier:"uncommon", layout:"card", stats:{hp:12,atk:6,def:8,mag:18,res:14,spd:10}, passives:["arcaneBond","archmage"], traits:["Tent-Wand"], lore:"Studies by lantern.", habitat:"Field tents.", tactics:"Bolts. Wards.", weaknesses:["metal"], resistances:["arcane"]}),
  m("dani_lion",        { name:"Dani Lion",          art:"uploads/dani lion.png",          factions:["beast","champion"],    elements:["light","wind"],  tier:"rare",   layout:"card", stats:{hp:20,atk:20,def:14,mag:8,res:10,spd:18}, passives:["divineSmite","packLeader"], traits:["Mane of Day"], lore:"Roars at the night until it shortens.", habitat:"Savanna ruins.", tactics:"Stalk. Pounce.", weaknesses:["shadow"], resistances:["light"]}),
  m("darkness_ziod",    { name:"Darkness Ziod",      art:"uploads/Darkness ziod the magical Warrior.png", factions:["warrior","mage","corrupted"], elements:["shadow","arcane"], tier:"elite", layout:"card", stats:{hp:22,atk:22,def:16,mag:22,res:18,spd:18}, passives:["shadowWard","sneakAttack"], traits:["Twin-Edged"], lore:"Trains in the off-hours of the moon.", habitat:"Sunless dojos.", tactics:"Cut. Cut. Cast.", weaknesses:["light"], resistances:["shadow","arcane"]}),
  m("death_dragon_bear",{ name:"Death Dragon Bear",  art:"uploads/Death Dragon Bear.png",  factions:["beast","dragonkin","undead"], elements:["shadow","blood"], tier:"elite", layout:"card", stats:{hp:24,atk:22,def:18,mag:12,res:16,spd:12}, passives:["raiseFromDead","bloodthirst"], traits:["Skull-Maw"], lore:"Two skeletons stitched together by hunger.", habitat:"Burial woods.", tactics:"Maul. Refuse to drop.", weaknesses:["light"], resistances:["shadow","blood"]}),
  m("death_plant",      { name:"Death Plant",        art:"uploads/Death Plant.png",        factions:["plant","corrupted"],   elements:["nature","poison","shadow"], tier:"rare", layout:"card", stats:{hp:18,atk:12,def:14,mag:16,res:14,spd:6}, passives:["rootsOfLife","venomous"], traits:["Pulse-Pod"], lore:"Blooms where the dirt is wrong.", habitat:"Mass graves; rotted gardens.", tactics:"Roots. Bleeds the soil.", weaknesses:["fire"], resistances:["nature","poison"]}),
  m("do_do_blazer",     { name:"Do Do Blazer",       art:"uploads/Do Do Blazer.png",       factions:["bird","corrupted"],    elements:["fire","wind"],   tier:"uncommon", layout:"card", stats:{hp:12,atk:10,def:8,mag:6,res:8,spd:16}, passives:["solarFlare"], traits:["Flight-Confused"], lore:"Re-extinct, briefly.", habitat:"Volcanic isles.", tactics:"Charges. Flaps.", weaknesses:["water"], resistances:["fire"]}),
  m("elemental_leaper", { name:"Elemental Leaper",   art:"uploads/Elemental Leaper.png",   factions:["elemental","beast"],   elements:["earth","wind"],  tier:"common", layout:"card", stats:{hp:10,atk:10,def:6,mag:10,res:8,spd:18}, passives:["swift"], traits:["Hop-Step"], lore:"Lands where it shouldn't.", habitat:"Cliff edges.", tactics:"Pounces.", weaknesses:["metal"], resistances:["earth","wind"]}),
  m("elem_eris",        { name:"Elemental Spirit Eris", art:"uploads/Elemental Spirit eris.png", factions:["elemental","spirit"], elements:["storm","sound"], tier:"rare", layout:"card", stats:{hp:16,atk:12,def:10,mag:20,res:16,spd:18}, passives:["weatherSummoner"], traits:["Argument-Born"], lore:"Wherever two voices rise.", habitat:"Court rooms; ruined senates.", tactics:"Splits sides.", weaknesses:["earth"], resistances:["storm","sound"]}),
  m("elem_fire",        { name:"Elemental Spirit — Fire", art:"uploads/Elemental Spirt Fire.png", factions:["elemental"], elements:["fire","lava"], tier:"common", layout:"card", stats:{hp:10,atk:14,def:6,mag:14,res:6,spd:12}, passives:["fireWard"], traits:["Coal-Heart"], lore:"Cannot remember winter.", habitat:"Forges.", tactics:"Burns.", weaknesses:["water"], resistances:["fire","lava"]}),
  m("elem_golem",       { name:"Elemental Spirit — Live Golem", art:"uploads/Elemental Spirt Live Golem.png", factions:["elemental","construct"], elements:["earth","crystal"], tier:"uncommon", layout:"card", stats:{hp:18,atk:12,def:18,mag:10,res:14,spd:6}, passives:["constructed","earthWard"], traits:["Walking Quarry"], lore:"Decided.", habitat:"Old mines.", tactics:"Walks. Crushes.", weaknesses:["sound"], resistances:["earth","crystal"]}),
  m("fire_boy",         { name:"Fire Boy",           art:"uploads/element Spirit Fire Boy.png", factions:["elemental"],    elements:["fire"],          tier:"common", layout:"card", stats:{hp:8,atk:8,def:4,mag:14,res:6,spd:14}, passives:["fireWard","sunbather"], traits:["Spark-Cheeked"], lore:"Loves a forge.", habitat:"Forge-towns.", tactics:"Sparks.", weaknesses:["water"], resistances:["fire"]}),
  m("wartar_kong",      { name:"Wartar Kong",        art:"uploads/element Spirit Wartar Kong.png", factions:["elemental","giant","beast"], elements:["earth","wind"], tier:"elite", layout:"card", stats:{hp:24,atk:20,def:20,mag:10,res:12,spd:8}, passives:["wallBreaker","tough"], traits:["Mountain-Punch"], lore:"Climbs by demolition.", habitat:"Cliff-cities.", tactics:"Punch. Climb. Punch.", weaknesses:["arcane"], resistances:["earth"]}),
  m("flaming_egg",      { name:"Flaming Egg of the Sun", art:"uploads/Flaming egg of the sun.png", factions:["bird","elemental"], elements:["fire","light"], tier:"uncommon", layout:"card", stats:{hp:14,atk:4,def:10,mag:16,res:14,spd:4}, passives:["fireWard","phoenixRebirth"], traits:["Almost-Bird"], lore:"It will hatch on the wrong day.", habitat:"Sun-altars.", tactics:"Waits.", weaknesses:["water"], resistances:["fire","light"]}),
  m("flaming_peacock",  { name:"Flaming Peacock of the Sun", art:"uploads/Flaming Peacock of the Sun.png", factions:["bird","celestial"], elements:["fire","light"], tier:"rare", layout:"card", stats:{hp:18,atk:14,def:10,mag:20,res:14,spd:18}, passives:["solarFlare","phoenixRebirth"], traits:["Eyed Tail"], lore:"Vain. Holy.", habitat:"Garden-shrines.", tactics:"Display. Burn.", weaknesses:["shadow"], resistances:["fire","light"]}),
  m("gokien",           { name:"Gokien",             art:"uploads/Gokien.png",             factions:["champion","monk","beast"], elements:["wind","spirit"], tier:"rare", layout:"card", stats:{hp:18,atk:18,def:12,mag:14,res:14,spd:22}, passives:["swift","sneakAttack"], traits:["Staff-Born"], lore:"A monkey by way of a sermon.", habitat:"Cloud temples.", tactics:"Sticks. Vaults.", weaknesses:["earth"], resistances:["wind","spirit"]}),
  m("grey_dragon",      { name:"Grey Dragon, Dragonic Knight", art:"uploads/Grey Dragon Dragonic Knight.png", factions:["dragonkin","warrior","champion"], elements:["metal","arcane"], tier:"legendary", layout:"card", stats:{hp:26,atk:22,def:24,mag:18,res:18,spd:14}, passives:["dragonsBoon","wardVsDragon"], traits:["Plated"], lore:"Knighted itself.", habitat:"Throne-keeps.", tactics:"Holds. Strikes once.", weaknesses:["sound"], resistances:["metal","arcane"]}),
  m("moonvulture",      { name:"Moonvulture",        art:"uploads/Moonvulture.png",        factions:["bird","undead"],       elements:["shadow","spirit"], tier:"uncommon", layout:"card", stats:{hp:14,atk:10,def:6,mag:8,res:8,spd:18}, passives:["sneakAttack"], traits:["Carrion Tide"], lore:"Patrols what dies.", habitat:"Old battlefields.", tactics:"Picks.", weaknesses:["light"], resistances:["shadow"]}),
  m("xeno_egg",         { name:"Xeno Egg",           art:"uploads/Xeno Egg.png",           factions:["alien","construct"],   elements:["void","corruption"], tier:"common", layout:"card", stats:{hp:14,atk:2,def:14,mag:6,res:12,spd:2}, passives:["constructed","xenoBond"], traits:["Patient"], lore:"Will be a problem.", habitat:"Hold-bays.", tactics:"Waits.", weaknesses:["fire"], resistances:["void"]}),
  m("xenoshell",        { name:"Xenoshell",          art:"uploads/Xenoshell.png",          factions:["alien","construct"],   elements:["metal","void"],  tier:"rare", layout:"card", stats:{hp:18,atk:14,def:18,mag:8,res:14,spd:10}, passives:["constructed","xenoBond"], traits:["Husk-Walker"], lore:"What's left when the host runs out.", habitat:"Hive corridors.", tactics:"Walks at you.", weaknesses:["arcane"], resistances:["metal","void"]}),
  m("xenotail_first",   { name:"Xenotail The First", art:"uploads/Xenotail The first.png", factions:["alien","champion","corrupted"], elements:["void","corruption","blood"], tier:"legendary", layout:"card", stats:{hp:26,atk:24,def:18,mag:18,res:18,spd:22}, passives:["xenoBond","predatorsEye"], traits:["Founder-Tail"], lore:"The one the hive remembers.", habitat:"Origin chamber.", tactics:"Hunts.", weaknesses:["fire","sound"], resistances:["void","corruption","blood"]}),
  m("xenotail_baby",    { name:"Xenotail (Baby)",    art:"uploads/xenotailbaby.png",       factions:["alien","beast"],       elements:["void"],          tier:"common", layout:"card", stats:{hp:8,atk:6,def:4,mag:4,res:4,spd:16}, passives:["xenoBond"], traits:["Wet-Born"], lore:"Just hatched.", habitat:"Nurseries.", tactics:"Skitters.", weaknesses:["fire"], resistances:["void"]}),
  m("yuki",             { name:"Yuki",               art:"uploads/Yuki.png",               factions:["spirit","champion"],   elements:["ice","spirit"],  tier:"rare", layout:"card", stats:{hp:18,atk:14,def:12,mag:18,res:18,spd:18}, passives:["iceWard","ambushSoul"], traits:["Snow-Stepper"], lore:"Walks where the snow forgets to crunch.", habitat:"Highland passes.", tactics:"Strikes from white.", weaknesses:["fire"], resistances:["ice","spirit"]}),
  m("scropirex",        { name:"Scropirex",          art:"uploads/scropirex.png",          factions:["beast","reptile","bug"], elements:["poison","earth"], tier:"elite", layout:"card", stats:{hp:24,atk:22,def:18,mag:10,res:14,spd:14}, passives:["venomous","trapHunter"], traits:["Two-Tailed"], lore:"Scorpion and rex disagreed in committee.", habitat:"Cracked salt-flats.", tactics:"Pincers, then poison.", weaknesses:["ice"], resistances:["poison","earth"]}),
  m("hitman",           { name:"Hitman",             art:"uploads/Hitman.png",             factions:["rogue","soldier","merchant"], elements:["shadow","metal"], tier:"rare", layout:"card", stats:{hp:16,atk:20,def:10,mag:6,res:10,spd:20}, passives:["sneakAttack","hairTrigger"], traits:["Contract-Bound"], lore:"Has a list. You're on it.", habitat:"City roofs; quiet rooms.", tactics:"One shot. One.", weaknesses:["light"], resistances:["shadow"]}),
  m("bounty_collector", { name:"Bounty Collector",   art:"uploads/Bounty Collector.png",   factions:["rogue","merchant","soldier"], elements:["metal","shadow"], tier:"rare", layout:"card", stats:{hp:18,atk:20,def:12,mag:6,res:10,spd:16}, passives:["sneakAttack","packTactics"], traits:["Quarry-Eyed"], lore:"Brings them back. Sometimes alive.", habitat:"Frontier towns.", tactics:"Patient. Lethal.", weaknesses:["arcane"], resistances:["metal"]}),
  m("street_king",      { name:"Street King VIP",    art:"uploads/Street King Vip.png",    factions:["champion","merchant","rogue"], elements:["metal","sound"], tier:"elite", layout:"card", stats:{hp:22,atk:18,def:14,mag:10,res:12,spd:14}, passives:["warlord","inspire"], traits:["Pavement-Crowned"], lore:"Owns the block; rents you the sidewalk.", habitat:"Neon alleys.", tactics:"Calls allies.", weaknesses:["light"], resistances:["metal","sound"]}),
  m("contractor",       { name:"Contractor",         art:"uploads/Contractor.png",         factions:["soldier","mercenary","rogue"].filter(x=>x!=='mercenary'), elements:["metal"], tier:"uncommon", layout:"card", stats:{hp:16,atk:16,def:12,mag:4,res:8,spd:12}, passives:["coolUnderPressure"], traits:["Paid in Full"], lore:"For hire.", habitat:"Outposts.", tactics:"Shoots straight.", weaknesses:["arcane"], resistances:["metal"]}),
  m("dr_timmy",         { name:"Dr Timmy, SCP Scientist", art:"uploads/Dr timmy SCP Scientist.png", factions:["scholar","artificer"], elements:["arcane","crystal"], tier:"uncommon", layout:"card", stats:{hp:12,atk:6,def:8,mag:18,res:14,spd:10}, passives:["archmage","xrayVision"], traits:["Clipboard-Armed"], lore:"Documents you before he stops you.", habitat:"Labs.", tactics:"Scan. Sedate.", weaknesses:["metal"], resistances:["arcane"]}),
  m("field_medic",      { name:"Field Medic",        art:"uploads/Fleld Medic.png",        factions:["soldier","scholar","champion"], elements:["light","spirit"], tier:"uncommon", layout:"card", stats:{hp:14,atk:8,def:10,mag:16,res:14,spd:12}, passives:["tideHealer","stabilize"], traits:["Bag-Heavy"], lore:"Keeps the line.", habitat:"Forward bases.", tactics:"Heal. Heal. Heal.", weaknesses:["shadow"], resistances:["light"]}),
  m("medic_drone",      { name:"Medic Drone",        art:"uploads/Medic Drone.png",        factions:["construct","artificer"], elements:["light","metal"], tier:"uncommon", layout:"card", stats:{hp:12,atk:4,def:10,mag:14,res:12,spd:14}, passives:["constructed","tideHealer"], traits:["Hover-Field"], lore:"Polite. Pulsed.", habitat:"Bay-decks.", tactics:"Patches.", weaknesses:["arcane"], resistances:["metal","light"]}),
  m("max_scrap",        { name:"Max the Scrap Mage", art:"uploads/Max The Scrap Mage.png", factions:["mage","artificer","scholar"], elements:["metal","arcane"], tier:"rare", layout:"card", stats:{hp:16,atk:10,def:12,mag:20,res:14,spd:12}, passives:["archmage","wallBreaker"], traits:["Bolt-Robe"], lore:"Spells held together with wire.", habitat:"Junk-towers.", tactics:"Cast. Smash.", weaknesses:["sound"], resistances:["metal","arcane"]}),
  m("mr_ascend",        { name:"Mr Ascend",          art:"uploads/Mr Ascend.png",          factions:["monk","champion","spirit"], elements:["light","wind","spirit"], tier:"elite", layout:"card", stats:{hp:22,atk:18,def:16,mag:20,res:18,spd:18}, passives:["forcedAscension","ironWill"], traits:["Upward-Bound"], lore:"Has practiced the leaving.", habitat:"Mountain decks.", tactics:"Closes distance. Rises.", weaknesses:["earth"], resistances:["light","spirit"]}),
  m("magical_azen",     { name:"Magical Warrior Azen", art:"uploads/Magical warrior Azen.png", factions:["warrior","mage","champion"], elements:["arcane","light"], tier:"elite", layout:"card", stats:{hp:22,atk:20,def:16,mag:20,res:16,spd:18}, passives:["divineSmite","warriorOath"], traits:["Star-Blade"], lore:"Sword in one hand, spell in the other.", habitat:"Hero-roads.", tactics:"Cast then cut.", weaknesses:["shadow"], resistances:["arcane","light"]}),
  m("rocus_baboom",     { name:"Rocus the Baboom",   art:"uploads/Rocus The Baboom.png",   factions:["beast","tribal","berserker"], elements:["fire","sound"], tier:"rare", layout:"card", stats:{hp:18,atk:20,def:12,mag:6,res:10,spd:16}, passives:["mobTactics","warriorOath"], traits:["Drum-Fisted"], lore:"Loud.", habitat:"Mesa villages.", tactics:"Charges with a yell.", weaknesses:["water"], resistances:["fire","sound"]}),
  m("rose_warrior",     { name:"Rose Warrior",       art:"uploads/Rose warrior.png",       factions:["warrior","plant","champion"], elements:["nature","blood"], tier:"rare", layout:"card", stats:{hp:18,atk:18,def:14,mag:10,res:12,spd:14}, passives:["thorns","rootsOfLife"], traits:["Thorn-Mail"], lore:"Blooms where she fights.", habitat:"Wild gardens.", tactics:"Strike. Bleed for it.", weaknesses:["fire"], resistances:["nature"]}),
  m("rapter_plant",     { name:"Rapter Plant",       art:"uploads/Rapter Plant.png",       factions:["plant","beast","corrupted"], elements:["nature","poison"], tier:"uncommon", layout:"card", stats:{hp:14,atk:14,def:8,mag:8,res:10,spd:14}, passives:["venomous","rootsOfLife"], traits:["Snap-Maw"], lore:"Hunts in the herb-rows.", habitat:"Overgrown fields.", tactics:"Lunge.", weaknesses:["fire"], resistances:["nature","poison"]}),
  m("robo_cano",        { name:"Robo Cano",          art:"uploads/Robo Cano.png",          factions:["construct","artificer"], elements:["metal","lava"], tier:"elite", layout:"card", stats:{hp:24,atk:22,def:20,mag:10,res:14,spd:8}, passives:["constructed","fireWard"], traits:["Volcanic-Plated"], lore:"They built a mountain a body.", habitat:"Industrial calderas.", tactics:"Lumbers. Ignites.", weaknesses:["water"], resistances:["metal","lava"]}),
  m("volcanic_tank",    { name:"Volcanic Tank",      art:"uploads/Volcanic Tank.png",      factions:["construct","artificer","soldier"], elements:["lava","metal"], tier:"elite", layout:"card", stats:{hp:26,atk:20,def:24,mag:6,res:14,spd:6}, passives:["constructed","fireWard","tough"], traits:["Tracked-Furnace"], lore:"Where it stops, the ground glasses.", habitat:"Forward ridges.", tactics:"Holds. Shells.", weaknesses:["water"], resistances:["lava","metal"]}),
  m("containment_tank", { name:"Containment Tank",   art:"uploads/Containment Tank.png",   factions:["construct","artificer","soldier"], elements:["metal","arcane"], tier:"elite", layout:"card", stats:{hp:26,atk:18,def:26,mag:10,res:16,spd:6}, passives:["constructed","wardVsCelestial"], traits:["Vault-Walls"], lore:"Built to keep a thing inside. The thing is inside.", habitat:"Foundation deeps.", tactics:"Holds. Holds.", weaknesses:["sound"], resistances:["metal","arcane"]}),
  m("cosmic_hunter",    { name:"Cosmic Hunter",      art:"uploads/Cosmic Hunter.png",      factions:["alien","rogue","champion"], elements:["void","light"], tier:"legendary", layout:"card", stats:{hp:24,atk:24,def:18,mag:18,res:18,spd:22}, passives:["predatorsEye","squadSight"], traits:["Star-Track"], lore:"Trophy-hunter from above the maps.", habitat:"High orbit; lonely peaks.", tactics:"Stalks. Trophies.", weaknesses:["earth"], resistances:["void","light"]}),
  m("ufbeamer",         { name:"UFBeamer",           art:"uploads/Ufbeamer.png",           factions:["alien","artificer"],   elements:["light","void"],  tier:"elite", layout:"card", stats:{hp:20,atk:18,def:16,mag:22,res:18,spd:14}, passives:["squadSight","weatherSummoner"], traits:["Tractor-Beam"], lore:"Lifts. Files.", habitat:"Upper sky.", tactics:"Beam. Abduct.", weaknesses:["storm"], resistances:["light","void"]}),
  m("spacve_jet",       { name:"Space Jet",          art:"uploads/Spacve Jet.png",         factions:["alien","artificer","soldier"], elements:["wind","metal"], tier:"rare", layout:"card", stats:{hp:18,atk:18,def:14,mag:10,res:12,spd:22}, passives:["swift","constructed"], traits:["Slip-Frame"], lore:"Faster than the air it pretends to use.", habitat:"Upper troposphere.", tactics:"Strafe.", weaknesses:["storm"], resistances:["wind","metal"]}),
  m("scp_helichopper",  { name:"SCP Helicopter",     art:"uploads/SCp-Helichoper.png",     factions:["soldier","artificer","construct"], elements:["metal","wind"], tier:"rare", layout:"card", stats:{hp:18,atk:16,def:14,mag:6,res:10,spd:18}, passives:["constructed","squadSight"], traits:["Rotor-Cold"], lore:"Lifts containment to wherever you weren't.", habitat:"Mid-altitude.", tactics:"Hover. Drop.", weaknesses:["storm"], resistances:["metal","wind"]}),
  m("scp_2747",         { name:"SCP-2747",           art:"uploads/SCP-2747.png",           factions:["eldritch","corrupted","construct"], elements:["void","corruption"], tier:"elite", layout:"card", stats:{hp:22,atk:14,def:18,mag:22,res:20,spd:8}, passives:["voidWard","magicalImmortal"], traits:["Pattern-Eater"], lore:"Stops being studied.", habitat:"Locked archives.", tactics:"Subtracts.", weaknesses:["light"], resistances:["void","corruption"]}),
  m("scp_738",          { name:"SCP-738",            art:"uploads/SCp-738.png",            factions:["demon","artificer"],   elements:["shadow","arcane"], tier:"elite", layout:"card", stats:{hp:22,atk:16,def:16,mag:22,res:20,spd:12}, passives:["inspire","wardVsCelestial"], traits:["Deal-Maker"], lore:"Always has a chair waiting.", habitat:"Contract rooms.", tactics:"Negotiates with your insides.", weaknesses:["light"], resistances:["shadow","arcane"]}),
  m("savage_cutthroat", { name:"Savage Demon Cutthroat", art:"uploads/Savage Demon cutthroat.png", factions:["demon","rogue","berserker"], elements:["blood","shadow"], tier:"rare", layout:"card", stats:{hp:18,atk:22,def:10,mag:8,res:8,spd:20}, passives:["sneakAttack","hellbound"], traits:["Throat-Knife"], lore:"Cheap. Final.", habitat:"Hell-alleys.", tactics:"Cut.", weaknesses:["light"], resistances:["blood","shadow"]}),
  m("savage_decorio",   { name:"Savage Demon Decorio", art:"uploads/Savage Demon Decorio.png", factions:["demon","cultist"],  elements:["fire","shadow"], tier:"elite", layout:"card", stats:{hp:22,atk:20,def:16,mag:18,res:16,spd:14}, passives:["hellbound","fireWard"], traits:["Hierarch"], lore:"Ranked. Polite. Murderous.", habitat:"Demonic chapter-houses.", tactics:"Commands.", weaknesses:["light"], resistances:["fire","shadow"]}),
  m("savage_gorzah",    { name:"Savage Demon Gorzah Cozmet", art:"uploads/Savage Demon Gorzah Cozmet.png", factions:["demon","berserker"], elements:["blood","fire"], tier:"legendary", layout:"card", stats:{hp:26,atk:26,def:18,mag:14,res:16,spd:16}, passives:["bloodthirst","hellbound","fireWard"], traits:["Blade-Crown"], lore:"Slaughter as administration.", habitat:"Pits.", tactics:"Charges twice.", weaknesses:["light"], resistances:["blood","fire"]}),
  m("savage_lukeage",   { name:"Savage Demon Lukeage", art:"uploads/Savage Demon Lukeage.png", factions:["demon","rogue"],     elements:["shadow","corruption"], tier:"rare", layout:"card", stats:{hp:18,atk:18,def:12,mag:14,res:14,spd:18}, passives:["sneakAttack","shadowWard"], traits:["Smile-Knife"], lore:"Polite up close.", habitat:"Cellar bars.", tactics:"Smile, stab.", weaknesses:["light"], resistances:["shadow","corruption"]}),
  m("savage_mist",      { name:"Savage Demon Magcal Mist", art:"uploads/Savage Demon Magcal Mist.png", factions:["demon","mage","spirit"], elements:["arcane","shadow"], tier:"rare", layout:"card", stats:{hp:18,atk:10,def:10,mag:22,res:18,spd:14}, passives:["mistDancer","ambushSoul"], traits:["Mist-Cloaked"], lore:"Heard before seen.", habitat:"Fog-banks.", tactics:"Drifts. Strikes.", weaknesses:["wind"], resistances:["arcane","shadow"]}),
  m("savage_dezmi",     { name:"Savage Demon Dezmi", art:"uploads/Savage Demon Savage Demon Dezmi .png", factions:["demon","berserker"], elements:["fire","blood"], tier:"elite", layout:"card", stats:{hp:22,atk:22,def:16,mag:12,res:14,spd:16}, passives:["bloodthirst","hellbound"], traits:["Twin-Horn"], lore:"Bigger and angrier.", habitat:"Old burns.", tactics:"Bull-rush.", weaknesses:["light"], resistances:["fire","blood"]}),
  m("the_crazy_one",    { name:"The Crazy One",      art:"uploads/The Crazy One.png",      factions:["corrupted","cultist","berserker"], elements:["psychic","corruption"], tier:"rare", layout:"card", stats:{hp:18,atk:18,def:10,mag:14,res:10,spd:18}, passives:["ironWill","moxie"], traits:["Off-Lever"], lore:"Will not stop laughing.", habitat:"Closed wards.", tactics:"Rushes.", weaknesses:["arcane"], resistances:["psychic"]}),
  m("the_old_man",      { name:"The Old Man",        art:"uploads/The Old Man.png",        factions:["spirit","scholar","cultist"], elements:["spirit","shadow"], tier:"elite", layout:"card", stats:{hp:18,atk:8,def:12,mag:24,res:22,spd:10}, passives:["archmage","ironWill"], traits:["Knows Things"], lore:"Has always been here.", habitat:"Watch-towers.", tactics:"Speaks the worst at you.", weaknesses:["fire"], resistances:["spirit","shadow"]}),
  m("the_watcher",      { name:"The Watcher",        art:"uploads/The watcher.png",        factions:["spirit","eldritch","scholar"], elements:["psychic","void"], tier:"elite", layout:"card", stats:{hp:20,atk:6,def:14,mag:24,res:22,spd:10}, passives:["xrayVision","magicWard"], traits:["Many-Eyed"], lore:"Counts every move you don't make.", habitat:"Mirror-rooms.", tactics:"Predicts. Negates.", weaknesses:["light"], resistances:["psychic","void"]}),
  m("the_moving_statue",{ name:"The Moving Statue",  art:"uploads/The Moving Statue.png",  factions:["construct","spirit","corrupted"], elements:["earth","spirit"], tier:"rare", layout:"card", stats:{hp:22,atk:18,def:18,mag:8,res:12,spd:8}, passives:["constructed","earthWard"], traits:["Don't-Blink"], lore:"Closer than it was.", habitat:"Garden mazes.", tactics:"Waits. Closes.", weaknesses:["sound"], resistances:["earth","spirit"]}),
  m("lady_ghost",       { name:"Lady Ghost",         art:"uploads/Lady Ghost.png",         factions:["undead","spirit","vampire"], elements:["shadow","spirit"], tier:"rare", layout:"card", stats:{hp:18,atk:12,def:8,mag:20,res:18,spd:14}, passives:["raiseFromDead","shadowWard"], traits:["Pale-Hand"], lore:"Doesn't remember being alive. Remembers being wronged.", habitat:"Old halls.", tactics:"Drifts. Drains.", weaknesses:["light"], resistances:["shadow","spirit"]}),
  m("spirit_ball",      { name:"Spirit Ball",        art:"uploads/Spirit ball.png",        factions:["spirit","elemental"], elements:["spirit","light"], tier:"common", layout:"card", stats:{hp:8,atk:4,def:4,mag:14,res:14,spd:16}, passives:["holyAura"], traits:["Wisp-Tail"], lore:"A small good thing.", habitat:"Glades.", tactics:"Drifts. Heals.", weaknesses:["shadow"], resistances:["spirit","light"]}),
  m("survivor_spirit",  { name:"Survivor Spirit",    art:"uploads/Survivor Spirt.png",     factions:["spirit","champion"], elements:["spirit","light"], tier:"uncommon", layout:"card", stats:{hp:14,atk:10,def:10,mag:16,res:16,spd:14}, passives:["holyAura","stabilize"], traits:["Last-Step"], lore:"Stays for one more turn.", habitat:"Ruined hospitals.", tactics:"Holds.", weaknesses:["shadow"], resistances:["spirit","light"]}),
  m("scum",             { name:"Scum",               art:"uploads/Scum.png",               factions:["corrupted","goblinoid","swarm"], elements:["corruption","poison"], tier:"common", layout:"card", stats:{hp:8,atk:8,def:4,mag:4,res:6,spd:12}, passives:["mobTactics"], traits:["Numbers-Bred"], lore:"There are more than this. There are always more.", habitat:"Slums.", tactics:"Crowd.", weaknesses:["fire"], resistances:["corruption","poison"]}),
  m("scum_self",        { name:"Scum Self-Detonator", art:"uploads/Scum Self Detonator.png", factions:["corrupted","goblinoid","cultist"], elements:["fire","corruption"], tier:"uncommon", layout:"card", stats:{hp:8,atk:18,def:4,mag:6,res:4,spd:12}, passives:["mobTactics","forcedAscension"], traits:["One-Shot"], lore:"Saves the last bit for everyone.", habitat:"Front lines.", tactics:"Runs. Pops.", weaknesses:["water"], resistances:["fire","corruption"]}),
  m("scum_boss",        { name:"Scum Boss",          art:"uploads/Scum boss.png",          factions:["corrupted","goblinoid","champion"], elements:["fire","corruption","blood"], tier:"elite", layout:"card", stats:{hp:24,atk:22,def:18,mag:8,res:14,spd:12}, passives:["mobTactics","warlord","bloodthirst"], traits:["Mob-Crowned"], lore:"Has a name no one writes down.", habitat:"Rebel quarters.", tactics:"Sends them in. Watches.", weaknesses:["light"], resistances:["fire","corruption"]}),
  m("shy_guy",          { name:"Shy Guy",            art:"uploads/Shy Guy.png",            factions:["spirit","corrupted"], elements:["shadow","corruption"], tier:"common", layout:"card", stats:{hp:10,atk:8,def:6,mag:8,res:8,spd:12}, passives:["sneakAttack"], traits:["Mask-Fixed"], lore:"Won't show you.", habitat:"Corners.", tactics:"Watches. Lunges.", weaknesses:["light"], resistances:["shadow"]}),
  m("scp_guard",        { name:"SCP Guard",          art:"uploads/Scp Guard.png",          factions:["soldier","champion"], elements:["metal","light"], tier:"uncommon", layout:"card", stats:{hp:16,atk:14,def:14,mag:4,res:10,spd:10}, passives:["guardian","coolUnderPressure"], traits:["Heavy-Gear"], lore:"Knows the protocol cold.", habitat:"Containment wings.", tactics:"Holds. Fires.", weaknesses:["arcane"], resistances:["metal"]}),
  m("scp_guard_knight", { name:"SCP Guard Knight",   art:"uploads/SCP Guard Knight.png",   factions:["soldier","warrior","champion"], elements:["metal","light"], tier:"rare", layout:"card", stats:{hp:20,atk:18,def:18,mag:6,res:12,spd:12}, passives:["guardian","warriorOath"], traits:["Plate-Knight"], lore:"Old order. New job.", habitat:"Deep wings.", tactics:"Holds. Strikes.", weaknesses:["arcane"], resistances:["metal","light"]}),
  m("scp_globen_guard", { name:"SCP Globen Guard",   art:"uploads/scp Globen Guard.png",   factions:["soldier","champion","artificer"], elements:["metal","arcane"], tier:"elite", layout:"card", stats:{hp:22,atk:18,def:20,mag:14,res:16,spd:10}, passives:["guardian","constructed"], traits:["Sealed-Suit"], lore:"Standardized last hope.", habitat:"Last halls.", tactics:"Won't fall.", weaknesses:["sound"], resistances:["metal","arcane"]}),
  m("survivor_dog",     { name:"Survivor Guard Dog", art:"uploads/survivor Guard dog.png", factions:["beast","soldier","champion"], elements:["metal","earth"], tier:"uncommon", layout:"card", stats:{hp:14,atk:14,def:10,mag:4,res:8,spd:18}, passives:["packLeader","trapDog"], traits:["Vest-Worn"], lore:"Best soldier on the squad.", habitat:"Field bases.", tactics:"Scouts. Bites.", weaknesses:["fire"], resistances:["metal","earth"]}),
  m("survivor_dual",    { name:"Survivor Guard Dual Blader", art:"uploads/Survivor Guard dual blader.png", factions:["soldier","warrior"], elements:["metal","wind"], tier:"rare", layout:"card", stats:{hp:18,atk:20,def:14,mag:4,res:10,spd:18}, passives:["sneakAttack","swift"], traits:["Two-Edge"], lore:"Twice the steel; half the wait.", habitat:"Field bases.", tactics:"Closes fast.", weaknesses:["arcane"], resistances:["metal"]}),
  m("survivor_mage",    { name:"Survivor Guard Mage", art:"uploads/Survivor Guard Mage.png", factions:["soldier","mage"],    elements:["arcane","metal"], tier:"rare", layout:"card", stats:{hp:14,atk:8,def:10,mag:20,res:16,spd:12}, passives:["archmage","squadSight"], traits:["Channel-Rifle"], lore:"Spells issued. Standardized.", habitat:"Forward bases.", tactics:"Casts at range.", weaknesses:["metal"], resistances:["arcane"]}),
  m("survivor_mech",    { name:"Survivor Guard Active Mech", art:"uploads/Survivor Guard Active Mech.png", factions:["construct","soldier","artificer"], elements:["metal","arcane"], tier:"elite", layout:"card", stats:{hp:24,atk:20,def:22,mag:12,res:14,spd:10}, passives:["constructed","guardian"], traits:["Pilot-Inside"], lore:"Half-armor, half-man.", habitat:"Forward bases.", tactics:"Holds.", weaknesses:["sound"], resistances:["metal","arcane"]}),
  m("survivor_shell",   { name:"Survivor Guard Mech Shell", art:"uploads/Survivor Guard Mech Shell.png", factions:["construct","soldier"], elements:["metal"], tier:"rare", layout:"card", stats:{hp:22,atk:14,def:24,mag:6,res:12,spd:8}, passives:["constructed","tough"], traits:["Empty-Suit"], lore:"Walks by itself when ordered.", habitat:"Front lines.", tactics:"Walks.", weaknesses:["arcane"], resistances:["metal"]}),
  m("survivor_spareman",{ name:"Survivor Guard Spareman", art:"uploads/Survivor Guard sparemen.png", factions:["soldier","champion"], elements:["metal"], tier:"uncommon", layout:"card", stats:{hp:16,atk:14,def:14,mag:4,res:10,spd:12}, passives:["guardian"], traits:["Always-Ready"], lore:"Holds spare ammo for the squad.", habitat:"Outposts.", tactics:"Steady fire.", weaknesses:["arcane"], resistances:["metal"]}),
  m("survivor_riflemen",{ name:"Survivor Guard Riflemen", art:"uploads/Suvivor Guard Riflemen.png", factions:["soldier"],         elements:["metal"],         tier:"common", layout:"card", stats:{hp:14,atk:14,def:10,mag:4,res:8,spd:12}, passives:["coolUnderPressure"], traits:["Squad-Drilled"], lore:"Standard. Lethal.", habitat:"Lines.", tactics:"Fires.", weaknesses:["arcane"], resistances:["metal"]}),
  m("survivor_monkey",  { name:"Survivor Mage Monkey", art:"uploads/Survivor mage monkey.png", factions:["mage","beast","soldier"], elements:["arcane","wind"], tier:"rare", layout:"card", stats:{hp:14,atk:8,def:8,mag:20,res:14,spd:18}, passives:["archmage","packLeader"], traits:["Wand-Tailed"], lore:"Trained somewhere irresponsible.", habitat:"Bases.", tactics:"Casts. Climbs.", weaknesses:["metal"], resistances:["arcane"]}),
  m("hero1",            { name:"Hero Survivor I",    art:"uploads/heor Survivor 1.png",    factions:["champion","soldier","warrior"], elements:["metal","light"], tier:"rare", layout:"card", stats:{hp:20,atk:18,def:16,mag:8,res:12,spd:14}, passives:["divineSmite","warriorOath"], traits:["First-Saved"], lore:"Survived because someone had to.", habitat:"Frontline.", tactics:"Leads.", weaknesses:["shadow"], resistances:["metal","light"]}),
  m("hero2",            { name:"Hero Survivor II",   art:"uploads/hero survior 2.png",     factions:["champion","soldier","rogue"], elements:["wind","metal"], tier:"rare", layout:"card", stats:{hp:18,atk:18,def:14,mag:8,res:10,spd:18}, passives:["sneakAttack","swift"], traits:["Quick-On"], lore:"Got out the back.", habitat:"Frontline.", tactics:"Flanks.", weaknesses:["earth"], resistances:["wind","metal"]}),
  m("hero3",            { name:"Hero Survivor III",  art:"uploads/heor Survivor 3.png",    factions:["champion","mage","soldier"], elements:["arcane","light"], tier:"rare", layout:"card", stats:{hp:18,atk:10,def:12,mag:20,res:16,spd:14}, passives:["archmage","squadSight"], traits:["Field-Reader"], lore:"Casts under fire.", habitat:"Backline.", tactics:"Bolts.", weaknesses:["metal"], resistances:["arcane","light"]}),
  m("hero4",            { name:"Hero Survivor IV",   art:"uploads/heor Survivor 4.png",    factions:["champion","scholar","soldier"], elements:["light","spirit"], tier:"rare", layout:"card", stats:{hp:18,atk:12,def:14,mag:18,res:18,spd:12}, passives:["holyAura","stabilize"], traits:["Field-Medic"], lore:"Keeps the squad alive.", habitat:"Frontline.", tactics:"Heals.", weaknesses:["shadow"], resistances:["light","spirit"]}),
  m("hero5",            { name:"Hero Survivor V",    art:"uploads/hero survior 5.png",     factions:["champion","soldier","rogue"], elements:["shadow","metal"], tier:"rare", layout:"card", stats:{hp:18,atk:20,def:14,mag:6,res:10,spd:20}, passives:["sneakAttack","hairTrigger"], traits:["Quiet-Walker"], lore:"Last in, first out.", habitat:"Frontline.", tactics:"Strikes from dark.", weaknesses:["light"], resistances:["shadow","metal"]}),
  m("hero7",            { name:"Hero Survivor VII",  art:"uploads/hero survior 7.png",     factions:["champion","soldier","warrior"], elements:["fire","metal"], tier:"rare", layout:"card", stats:{hp:20,atk:20,def:16,mag:8,res:10,spd:14}, passives:["bloodthirst","warriorOath"], traits:["Burn-Bright"], lore:"Won't die easily.", habitat:"Frontline.", tactics:"Charges.", weaknesses:["water"], resistances:["fire","metal"]}),
  m("ualti_element",    { name:"Ualti, Element Magician", art:"uploads/ualti Element Magician.png", factions:["mage","elemental"],  elements:["arcane","fire","water","earth","wind"], tier:"elite", layout:"card", stats:{hp:18,atk:8,def:12,mag:26,res:20,spd:12}, passives:["archmage","weatherweaver"], traits:["Quad-Sigil"], lore:"Holds the corners of weather.", habitat:"Tower spires.", tactics:"Rotates elements.", weaknesses:["metal"], resistances:["arcane"]}),
  m("ualti_warlock",    { name:"Ualti, Warlock of Abra", art:"uploads/ualti warlock of Abra.png", factions:["mage","cultist","fairy"], elements:["arcane","psychic"], tier:"elite", layout:"card", stats:{hp:18,atk:8,def:10,mag:26,res:22,spd:12}, passives:["archmage","mistDancer"], traits:["Pact-Eyed"], lore:"Borrows. Pays in increments.", habitat:"Bargain-rooms.", tactics:"Hexes.", weaknesses:["metal"], resistances:["arcane","psychic"]}),
  m("ualti_wizard",     { name:"Ualti, Wizard of Elements", art:"uploads/ualti wizard of Elements.png", factions:["mage","scholar","elemental"], elements:["fire","water","earth","wind"], tier:"elite", layout:"card", stats:{hp:18,atk:8,def:12,mag:26,res:20,spd:12}, passives:["archmage","sunbather"], traits:["Robe-Bound"], lore:"Studies all four corners.", habitat:"Tower libraries.", tactics:"Triples.", weaknesses:["metal"], resistances:["arcane"]}),
  m("weed_mage",        { name:"Weed Mage",          art:"uploads/Weed Mage.png",          factions:["mage","plant","scholar"], elements:["nature","poison"], tier:"rare", layout:"card", stats:{hp:16,atk:8,def:10,mag:22,res:16,spd:10}, passives:["archmage","rootsOfLife"], traits:["Moss-Robed"], lore:"Studies the green.", habitat:"Old groves.", tactics:"Roots first.", weaknesses:["fire"], resistances:["nature","poison"]}),
  m("d_class_mage",     { name:"D-Class Mage",       art:"uploads/Dclass mage.png",        factions:["mage","cultist","corrupted"], elements:["arcane","shadow"], tier:"uncommon", layout:"card", stats:{hp:14,atk:8,def:8,mag:18,res:14,spd:10}, passives:["archmage"], traits:["Orange-Suit"], lore:"Cheap labor. Dangerous results.", habitat:"Test cells.", tactics:"Bolts.", weaknesses:["metal"], resistances:["arcane"]}),
  m("little_grey",      { name:"Little Grey",        art:"uploads/Little Grey.png",        factions:["alien","scholar"],     elements:["psychic","void"], tier:"common", layout:"card", stats:{hp:10,atk:6,def:6,mag:14,res:12,spd:14}, passives:["lucidThinker"], traits:["Big-Eyed"], lore:"Asks first. Probes second.", habitat:"Saucers.", tactics:"Mind.", weaknesses:["sound"], resistances:["psychic","void"]}),
  m("men_in_black",     { name:"Men in Black",       art:"uploads/Men In Black.png",       factions:["soldier","artificer","cultist"], elements:["shadow","arcane"], tier:"rare", layout:"card", stats:{hp:16,atk:14,def:14,mag:14,res:14,spd:14}, passives:["xrayVision","squadSight"], traits:["Neuralizer"], lore:"Cleans up after.", habitat:"Anywhere with witnesses.", tactics:"Erases.", weaknesses:["sound"], resistances:["shadow","arcane"]}),
  m("blackmarket",      { name:"Blackmarket",        art:"uploads/Blackmarket icon.png",   factions:["merchant","rogue"],   elements:["shadow","metal"], tier:"uncommon", layout:"card", stats:{hp:14,atk:8,def:10,mag:8,res:10,spd:14}, passives:["inspire"], traits:["Coin-Eyed"], lore:"Buys, sells, fences.", habitat:"Backalleys.", tactics:"Trades.", weaknesses:["light"], resistances:["shadow"]}),
  m("cold_cash",        { name:"Cold Hard Cash",     art:"uploads/cold hard cash.png",     factions:["construct","merchant"], elements:["metal","ice"], tier:"common", layout:"card", stats:{hp:6,atk:2,def:6,mag:4,res:4,spd:2}, passives:["inspire"], traits:["Cold-Stack"], lore:"Doesn't talk.", habitat:"Vaults.", tactics:"Sits.", weaknesses:["sound"], resistances:["metal","ice"]}),
  m("corny_man",        { name:"Corny Man",          art:"uploads/Corny Man.png",          factions:["plant","spirit","corrupted"], elements:["nature","corruption"], tier:"uncommon", layout:"card", stats:{hp:14,atk:10,def:10,mag:8,res:10,spd:10}, passives:["rootsOfLife"], traits:["Husk-Body"], lore:"Last harvest's friend.", habitat:"Fields.", tactics:"Stands. Strikes.", weaknesses:["fire"], resistances:["nature","corruption"]}),
  m("krystal_diamond",  { name:"Krystal Anomaly Diamondback", art:"uploads/Krystal Anomaly Diamond back.png", factions:["beast","reptile","construct"], elements:["crystal","poison"], tier:"elite", layout:"card", stats:{hp:22,atk:18,def:22,mag:12,res:18,spd:12}, passives:["coldScales","constructed"], traits:["Geode-Hide"], lore:"Scales like cut stones.", habitat:"Crystal canyons.", tactics:"Strikes. Bleeds.", weaknesses:["sound"], resistances:["crystal","poison"]}),
  m("divine_rain",      { name:"Divine Rain",        art:"uploads/Divine Rain.png",        factions:["spirit","celestial","elemental"], elements:["water","light"], tier:"rare", layout:"card", stats:{hp:18,atk:8,def:12,mag:22,res:18,spd:14}, passives:["tideHealer","rainmaker"], traits:["Falling-Soft"], lore:"Heals from the sky.", habitat:"Holy uplands.", tactics:"Falls.", weaknesses:["fire"], resistances:["water","light"]}),
  m("divine_rain_kalon",{ name:"SCP Divine Rain (Kalon)", art:"uploads/SCP Divine Rain Kalon Form..png", factions:["celestial","champion","elemental"], elements:["water","light","arcane"], tier:"legendary", layout:"card", stats:{hp:24,atk:14,def:16,mag:28,res:24,spd:18}, passives:["tideHealer","rainmaker","forcedAscension"], traits:["Risen-Form"], lore:"The rain stops being rain.", habitat:"After-storm halls.", tactics:"Tides.", weaknesses:["earth"], resistances:["water","light"]}),
  m("stinkshark",       { name:"StinkShark",         art:"uploads/StinkShark.png",         factions:["beast","aquatic","corrupted"], elements:["water","poison"], tier:"rare", layout:"card", stats:{hp:18,atk:18,def:10,mag:8,res:10,spd:18}, passives:["venomous","tideHealer"], traits:["Reeking-Wake"], lore:"You smell it first.", habitat:"Polluted shallows.", tactics:"Charges.", weaknesses:["light"], resistances:["water","poison"]}),
  m("sparta_commander", { name:"Sparta Commander Paul", art:"uploads/Sparta Commander Paul.png", factions:["warrior","soldier","champion"], elements:["metal","fire"], tier:"elite", layout:"card", stats:{hp:24,atk:22,def:20,mag:6,res:12,spd:12}, passives:["warlord","warriorOath","guardian"], traits:["Crest-Crowned"], lore:"This is a job.", habitat:"Phalanx ranks.", tactics:"Holds line.", weaknesses:["arcane"], resistances:["metal","fire"]}),
  m("sparta_spartan",   { name:"Sparta Spartan",     art:"uploads/Sparta Spartan.png",     factions:["warrior","soldier"],   elements:["metal"],         tier:"uncommon", layout:"card", stats:{hp:18,atk:16,def:18,mag:4,res:10,spd:10}, passives:["warriorOath","guardian"], traits:["Shield-Side"], lore:"Stands.", habitat:"Phalanx.", tactics:"Holds.", weaknesses:["arcane"], resistances:["metal"]}),
];

// Bookmark / order: alphabetical default
MS.DEFAULT_ORDER = [...MS.MONSTERS].sort((a,b)=>a.name.localeCompare(b.name)).map(x=>x.id);
